product card
mate-academy/layout_product-cards pull request #1064
Opened 2021-12-06 17:57 UTC by E-Sharpilo

- [DEMO LINK](https://e-sharpilo.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://e-sharpilo.github.io/layout_product-cards/report/html_report/)

2021-12-07 10:09 UTC, varseniuk requested changes
Все добре, але давай використовувати відповідні теги для текстової інофрмації

2021-12-07 10:09 UTC, varseniuk commented on src/index.html
> +      </div>
```suggestion
      <h3 class="card__title">
        Моноблок APPLE A1419 iMac 27" Retina 5K (MNED2UA/A)
      </h3>
```
Семантично це заголовок

2021-12-07 10:09 UTC, varseniuk commented on src/index.html
> +      </div>
Тут також текстова інофрмація. Використовуй теги p чи span для тексту

2021-12-07 10:09 UTC, varseniuk commented on src/index.html
> +          Отзывов: <span>5</span>
```suggestion
          <span>Отзывов: 5</span>
```

2021-12-07 10:44 UTC, E-Sharpilo commented on src/index.html
> +          Отзывов: <span>5</span>
ну тут была логика обернуть только цифру в спан) чтобы через бэк ее можно было выводить) ведь покличество отзывов не статичная информация

2021-12-07 18:02 UTC, vkryvytskyy submitted a review, later dismissed

2021-12-07 18:02 UTC, vkryvytskyy commented on src/style.css
> +  border: 1px solid #00acdc;
Сделай чтобы border был у кнопки изначально, сейчас при наведении текст смещается

2021-12-07 18:02 UTC, vkryvytskyy commented on src/style.css
> +  max-width: 53px;
Откуда взялось 53px?

2021-12-07 18:02 UTC, vkryvytskyy commented on src/style.css
> +  padding-bottom: 24px;
Если тебе надо задать отступ до следующего элемента - используй margin

2021-12-07 18:02 UTC, vkryvytskyy commented on src/style.css
> +  padding-bottom: 4px;
margin?

2021-12-07 18:02 UTC, vkryvytskyy commented on src/style.css
> +  padding-bottom: 16px;
margin?

2021-12-08 09:40 UTC, varseniuk approved these changes

2024-12-28 15:32 UTC, closed without merging