myProdyctCard
mate-academy/layout_product-cards pull request #1137
Opened 2022-01-21 08:54 UTC by VladBrynzia

- [DEMO LINK](https://vladbrynzia.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://vladbrynzia.github.io/layout_product-cards/report/html_report/)

2022-01-21 11:37 UTC, mariiishka requested changes
в целом неплохо:smiley:, но нужно еще раз пройтись по [checklist](https://github.com/mate-academy/layout_product-cards/blob/master/checklist.md)

2022-01-21 11:37 UTC, mariiishka commented on src/index.html
> +            <div class="stars"></div>
[3 пункт](https://github.com/mate-academy/layout_product-cards/blob/master/checklist.md)  
и плюс - If you change stars--4 modifier to stars--2 or other - number of selected stars should change correctly.

2022-01-21 11:37 UTC, mariiishka commented on src/style.css
> +}
для каждого блока нужно создать отдельный css файл - [10 пункт](https://github.com/mate-academy/layout_product-cards/blob/master/checklist.md)

2022-01-21 11:37 UTC, mariiishka commented on src/style.css
> +  margin: 10px;
блоку лучше не добавлять такие стили - [6 пункт](https://github.com/mate-academy/layout_product-cards/blob/master/checklist.md)

2022-01-21 11:37 UTC, mariiishka commented on src/index.html
> +          <div class="rating">
можно не создавать отдельный блок, лучше описывать как элемент блока card, то есть не rating, а card__rating - [5 пункт](https://github.com/mate-academy/layout_product-cards/blob/master/checklist.md)

2022-01-21 11:37 UTC, mariiishka commented on src/style.css
> +  font-weight: 700;
лишняя строчка, по дефолту ширина тоже 700

2022-01-21 11:37 UTC, mariiishka commented on src/style.css
> +  padding-right: 56px;
почему бы не сделать display: block; и указать только вертикальные падинги, тогда при hover не нужно будет опять их менять

2022-01-21 11:37 UTC, mariiishka commented on src/style.css
> +  padding: 0 16px;
лучше указать падинги для блока (родителя), чтобы не ставить каждому элементу отдельно

2022-01-21 11:37 UTC, mariiishka commented on src/index.html
> +          <p class="code">Код товара: 195434</p>
нужно перенести текст на новую строчку

2022-01-24 13:36 UTC, mariiishka requested changes
не вижу новых фалов css, скорее всего не добавились, а по html отлично получилось!)

2022-01-24 13:36 UTC, mariiishka commented on src/index.html
> +          alt="#"
тут лучше прописать вот это - Моноблок APPLE A1419 iMac 27" Retina 5K (MNED2UA/A)

2022-01-24 13:36 UTC, mariiishka commented on src/index.html
> +            <a href="#buyNow" class="card__button-a">
и тут тоже
```suggestion
            <a href="#buyNow" class="card__button-link">
```

2022-01-24 13:36 UTC, mariiishka commented on src/index.html
> +            <p class="card__rating-p">Отзывов: 5</p>
думаю не стоит писать название тега в классе
```suggestion
            <p class="card__rating-value">Отзывов: 5</p>
```

2022-01-24 16:29 UTC, mariiishka approved these changes

2022-01-24 16:29 UTC, mariiishka commented on src/card.css
> +}
этот элемент не является частью блока card, поэтому должен быть в другом файле

2022-01-24 16:29 UTC, mariiishka commented on src/card.css
> +  color: #060b35;
можно вынести в отдельную переменную

2022-01-24 16:29 UTC, mariiishka commented on src/card.css
> +  color: #616070;
тоже в отдельную

2022-01-24 16:29 UTC, mariiishka commented on src/card.css
> +  color: #00acdc;
и этот цвет тоже

2022-01-24 16:29 UTC, mariiishka commented on src/card.css
> +  border: 1px solid #00acdc;
border лучше прописать по дефолту, так как кнопка сейчас немного прыгает, + можно добавить transition для color и background

2022-01-24 16:29 UTC, mariiishka commented on src/rating.css
> +}
пропиши стили для каждого модификатора (stars--1 - stars--5), когда в html меняешь модификатор, должно меняться кол-во желтых звездочек, цифра у модификатора соответствует кол-ву цветных звезд

2022-01-24 17:07 UTC, VladBrynzia commented on src/card.css
> +  border: 1px solid #00acdc;
fixed

2022-01-24 17:07 UTC, VladBrynzia commented on src/rating.css
> +}
fixed

2022-01-25 10:18 UTC, Ihor-Karpyn requested changes
Almost done

2022-01-25 10:18 UTC, Ihor-Karpyn commented on src/card.css
> +  border-radius: 5px;
add pading: 32px 16px 16px

2022-01-25 10:18 UTC, Ihor-Karpyn commented on src/card.css
> +  padding: 32px 19px;
for internal indents using margin, let's fix in all places
```suggestion
  display: block;
  margin: 0 auto 40;
```

2022-01-25 10:18 UTC, Ihor-Karpyn commented on src/card.css
> +  padding-bottom: 0;
margin-bottom

```suggestion
```

2022-01-25 10:18 UTC, Ihor-Karpyn commented on src/card.css
> +  padding: 4px 16px;
margin-bottom

```suggestion
```

2022-01-25 10:18 UTC, Ihor-Karpyn commented on src/card.css
> +  margin: 12px;
margin-bottom

```suggestion
```

2022-01-25 10:18 UTC, Ihor-Karpyn commented on src/card.css
> +  margin-left: 18px;
redundant
```suggestion
```

2022-01-25 10:18 UTC, Ihor-Karpyn commented on src/card.css
> +  padding: 0 16px;
margin-bottom

```suggestion
```

2022-01-25 10:18 UTC, Ihor-Karpyn commented on src/card.css
> +  margin: 11px 0;
margin-bottom

```suggestion
```

2022-01-25 10:18 UTC, Ihor-Karpyn commented on src/card.css
> +  margin: 11px 0;
redundant

```suggestion
```

2022-01-25 10:18 UTC, Ihor-Karpyn commented on src/card.css
> +  margin: 5px 16px 16px;
margin redundat here
add height and width 100%

```suggestion
```

2022-01-25 10:18 UTC, Ihor-Karpyn commented on src/main.css
> +}
margin redundant here, move card width to card.css

2022-01-25 10:18 UTC, Ihor-Karpyn commented on src/index.html
> +      <div class="main__card card" data-qa="card">
```suggestion
      <div class="card" data-qa="card">
```

2022-01-25 10:18 UTC, Ihor-Karpyn commented on src/index.html
> +        <div class="card__content">
wrapper redundant here

2022-01-25 10:18 UTC, Ihor-Karpyn commented on src/index.html
> +          <div class="card__button" data-qa="hover">
wrapper redundant here

2022-01-25 12:14 UTC, Ihor-Karpyn approved these changes
LGTM

2022-12-14 15:41 UTC, closed without merging