initial commit
mate-academy/layout_product-cards pull request #1145
Opened 2022-01-21 17:00 UTC by antch8

[DEMO LINK](https://antch8.github.io/layout_product-cards/)
[TEST REPORT LINK](https://antch8.github.io/layout_product-cards/report/html_report/)

2022-01-21 18:54 UTC, krolich500grn approved these changes
Well done 🔥

2022-01-21 18:54 UTC, krolich500grn commented on src/index.html
> +        </div>
Тут тільки не діви, а щось більш семантичне варто зробити

2022-01-24 10:49 UTC, Ihor-Karpyn requested changes
Almost done

2022-01-24 10:49 UTC, Ihor-Karpyn commented on src/styles/card/components/price.css
> +  margin: 0 0 16px;
BEM

2022-01-24 10:49 UTC, Ihor-Karpyn commented on src/styles/card/components/stars.css
> +  margin: 0 0 24px;
BEM

2022-01-24 10:49 UTC, Ihor-Karpyn commented on src/styles/card/components/stars.css
> +.card-stars__feedback {
move to card-stars.css

2022-01-24 10:49 UTC, Ihor-Karpyn commented on src/styles/card/components/stars.css
> +.card-stars {
move to card-stars.css

2022-01-24 12:31 UTC, Ihor-Karpyn requested changes
https://www.loom.com/share/1acdb97b58864ca0844d88cb81faec4d

2024-12-03 04:00 UTC, closed without merging