Product card iMac
mate-academy/layout_product-cards pull request #1147
Opened 2022-01-21 21:15 UTC by max-shlikhta

- [DEMO](https://max-shlikhta.github.io/layout_product-cards/)
- [TEST](https://max-shlikhta.github.io/layout_product-cards/report/html_report/)

2022-01-22 09:44 UTC, antch8 approved these changes
дуже добре 👍

p.s. спробуй розділяти стилі по різним файлам (пункт 10 чеклісту)

2022-01-22 09:44 UTC, antch8 commented on src/index.html
> +    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="anonymous">
більше 3-х атрибутів треба переносити
тут атрибут crossorigin не обов'язковий

2022-01-22 09:44 UTC, antch8 commented on src/index.html
> +            <div class="stars__grup">
*group

2022-01-22 09:44 UTC, antch8 commented on src/style.css
> +  font-style: normal;
це можна не вказувати)

2022-01-22 09:44 UTC, antch8 commented on src/style.css
> +  background-image: url(images/imac-side.jpg);
🔥

2022-01-22 09:44 UTC, antch8 commented on src/style.css
> +.stars__star:last-child {
пункт 3 чеклісту
при зміні модифікатору має змінюватись кількість зірок

2022-01-22 09:44 UTC, antch8 commented on src/style.css
> +  transition: all 0.3s ease;
спробуй задавати transition для конкретного правила (transition: color 0.3s ease, background-color 0.3s ease)
так само для 39 строчки

2022-01-22 19:06 UTC, GoDfreE25 requested changes

2022-01-22 19:06 UTC, GoDfreE25 commented on src/product-card_content.css
> +  color: #060b35;
Я б радив кольори винести в окрумі змінні бщоб вони були в 1 місці

2022-01-22 19:06 UTC, GoDfreE25 commented on src/product-card_content.css
> +}
Пункт  10 [Чекліст](https://github.com/mate-academy/layout_product-cards/blob/master/checklist.md)

2022-01-23 10:54 UTC, GoDfreE25 approved these changes

2022-01-23 10:54 UTC, GoDfreE25 commented on src/product-card_default.css
> +}
🔥

2022-01-23 10:54 UTC, GoDfreE25 commented on src/style.css
> +@import "./product-card_rating.css";
Тепер все по окремих блоках 🔥

2022-01-24 12:05 UTC, Ihor-Karpyn requested changes

2022-01-24 12:05 UTC, Ihor-Karpyn commented on src/product-card_content.css
> +}
block element by defaylt stay one below other, flex and wrapper redundant here

```suggestion
```

2022-01-24 12:05 UTC, Ihor-Karpyn commented on src/product-card_content.css
> +  margin: 0 auto 4px;
```suggestion
  margin-bottom: 4px;
```

2022-01-24 12:05 UTC, Ihor-Karpyn commented on src/product-card_content.css
> +  margin: 0;
create reset.css file and move reset style there

2022-01-24 12:05 UTC, Ihor-Karpyn commented on src/product-card_content.css
> +  margin-top: 24px;
use only margin-bottom and margin-right

add margi-bottom to prev element

2022-01-24 12:05 UTC, Ihor-Karpyn commented on src/product-card_content.css
> +  margin: 0;
reset.css
```suggestion
```

2022-01-24 12:05 UTC, Ihor-Karpyn commented on src/product-card_content.css
> +  margin: 0;
reset.css
```suggestion
```

2022-01-24 12:05 UTC, Ihor-Karpyn commented on src/product-card_content.css
> +  margin-top: 16px;
add margin-bottom to prev element
```suggestion
```

2022-01-24 12:05 UTC, Ihor-Karpyn commented on src/product-card_default.css
> +  margin: 0;
reset.css

2022-01-24 12:05 UTC, Ihor-Karpyn commented on src/product-card_default.css
> +  font-family: Roboto, sans-serif;
normalize.css

2022-01-24 12:05 UTC, Ihor-Karpyn commented on src/product-card_default.css
> +.card {
move to card.css

2022-01-24 12:05 UTC, Ihor-Karpyn commented on src/product-card_image.css
> +.card__image {
move all of this style to card.css

2022-01-24 12:05 UTC, Ihor-Karpyn commented on src/product-card_image.css
> +.card__image:hover .card__photo {
BEM

2022-01-24 12:05 UTC, Ihor-Karpyn commented on src/product-card_rating.css
> +.card__rating {
move to card .css and rename this file to stars.css

2022-01-24 12:05 UTC, Ihor-Karpyn commented on src/product-card_rating.css
> +.card__reviews {
move to card.css

2022-01-25 10:26 UTC, Ihor-Karpyn approved these changes
Good job

2025-08-31 09:33 UTC, closed without merging