Product cards HW
mate-academy/layout_product-cards pull request #1152
Opened 2022-01-22 19:16 UTC by Ostafii4uk

- [DEMO LINK](https://Ostafii4uk.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://Ostafii4uk.github.io/layout_product-cards/report/html_report/)

2022-01-23 17:29 UTC, Andr1yK requested changes
Потріно переписати структуру БЕМ[(Пункт 4 та 5 в чеклісті)](https://github.com/mate-academy/layout_product-cards/blob/master/checklist.md), а також поділити `style.css` на декілька файлів з блоками [(Пункт 10 в чеклісті)](https://github.com/mate-academy/layout_product-cards/blob/master/checklist.md)

Потрібно ще попрацювати, проте хороший страт😎🔥

2022-01-23 17:29 UTC, Andr1yK commented on src/index.html
> +          class="product-card-image"
А де елементи, я бачу тут тільки блоки?😅 Якщо писати по БЕМу, то `product-card` в тебе буде блоком, а уже зображення елементом з класом `product-card__image`
В коді нижче також потрібно це виправити)

2022-01-23 17:29 UTC, Andr1yK commented on src/index.html
> +          </div>
А чому б просто не використати блок stars з [минулої роботи](https://github.com/Ostafii4uk/layout_stars/tree/develop/) і також це вказано в [чеклісті пункт 3](https://github.com/mate-academy/layout_product-cards/blob/master/checklist.md)?

2022-01-23 17:29 UTC, Andr1yK commented on src/style.css
> +}
Це також краще викорисатати з минулої роботи (stars)

2022-01-24 08:52 UTC, Ostafii4uk commented on src/index.html
> +          class="product-card-image"
And now I understood that)

2022-01-24 08:53 UTC, Ostafii4uk commented on src/index.html
> +          </div>
Got it

2022-01-24 08:54 UTC, Ostafii4uk commented on src/style.css
> +}
Ok

2022-01-24 09:54 UTC, Andr1yK requested changes
З БЕМом бачу вже розібрався, **молодець**, ще трошки пофіксити і зразу ж апрув, так тримати🔥😎

2022-01-24 09:54 UTC, Andr1yK commented on src/index.html
> +        <div class="rate product-card__rate">
Сумніваюсь, що тобі потрібно створювати ще й блок для rate, в цій роботі як написано в чеклісті([пункт 5](https://github.com/mate-academy/layout_product-cards/blob/master/checklist.md))

2022-01-24 09:54 UTC, Andr1yK commented on src/index.html
> +        <div class="price product-card__price">
також і тут

2022-01-24 09:54 UTC, Andr1yK commented on src/style.css
> +}
Також потрібно створити для кожного блоку свій файл (для блоку stars створити stars.css і тд)

2022-01-24 10:03 UTC, Ostafii4uk commented on src/index.html
> +        <div class="rate product-card__rate">
Блок rate потрібен для флексу двох 'елементів' (1-ий це блок зірочок і 2-ий це текст 'Отзывов: 5'). Мені так простіше розкласти елементи.

2022-01-24 10:04 UTC, Ostafii4uk commented on src/index.html
> +        <div class="price product-card__price">
Такий самий принцип як із rate

2022-01-24 10:17 UTC, Ostafii4uk commented on src/style.css
> +}
Створено

2022-01-24 11:38 UTC, Ihor-Karpyn approved these changes
LGTM, check comments please

2022-01-24 11:38 UTC, Ihor-Karpyn commented on src/index.html
> +        <h1 class="product-card__title">
There are a lot of card in catalog, but in the page can be only one h1, so for card h2 will better

2022-01-24 11:38 UTC, Ihor-Karpyn commented on src/index.html
> +          <p class="price__title">
```suggestion
          <h3 class="price__title">
```

2022-01-24 11:38 UTC, Ihor-Karpyn commented on src/style.css
> +  margin: 0 0 4px;
add reset.css and reset style for p, h1, h2...

2022-01-24 11:38 UTC, Ihor-Karpyn commented on src/style.css
> +  margin: 0;
```suggestion
```

add reset css file, fixed in all places
```suggestion
```

2022-01-25 07:49 UTC, closed without merging