Create product card
mate-academy/layout_product-cards pull request #1206
Opened 2022-02-17 22:25 UTC by ivan-kadykalo

- [DEMO LINK](https://ivan-kadykalo.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://ivan-kadykalo.github.io/layout_product-cards/report/html_report/)

2022-02-21 09:30 UTC, YegorKochetkov requested changes
good job)

2022-02-21 09:30 UTC, YegorKochetkov commented on src/index.html
> +    <!-- Fonts -->
redundant comments (also below the document)

2022-02-21 09:30 UTC, YegorKochetkov commented on src/index.html
> +    <form
in fact, it is not a form. better use section or article

2022-02-21 09:30 UTC, YegorKochetkov commented on src/index.html
> +        class="image card__image"
redundant class `image`

2022-02-21 09:30 UTC, YegorKochetkov commented on src/index.html
> +      <h2 class="name card__title">
redundant class `name`
(also below the document)

2022-02-21 09:30 UTC, YegorKochetkov commented on src/index.html
> +      <div class="price card__price">
redundant class. you have `card__price`, why do you need `price`?

2022-02-21 09:30 UTC, YegorKochetkov commented on src/index.html
> +        class="button card__button"
redundant class

2022-02-21 09:30 UTC, YegorKochetkov commented on src/style_blocks/elements.css
> +  height: 40px;
better put first block model modifier, then font modifier

2022-02-22 09:01 UTC, MaksimusCRS approved these changes
Good job!

2022-02-22 09:01 UTC, MaksimusCRS commented on src/index.html
> +      <p class="code card__code">
```suggestion
      >
      
      <h2 class="card__title">
        Моноблок APPLE A1419 iMac 27" Retina 5K (MNED2UA/A)
      </h2>
      
      <p class="code card__code">
```

2022-02-22 09:01 UTC, MaksimusCRS commented on src/index.html
> +      <p class="code card__code">
Делай отступы между тегами, что бы было легче читать твой код

2023-08-08 17:41 UTC, closed without merging