cards
mate-academy/layout_product-cards pull request #1282
Opened 2022-03-23 06:58 UTC by Havrysh

- [DEMO LINK](https://Havrysh.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://Havrysh.github.io/layout_product-cards/report/html_report/)

2022-03-23 11:50 UTC, varseniuk requested changes
Тести не задеплоєні

2022-03-23 11:50 UTC, varseniuk commented on readme.md
> +- [DEMO LINK](https://Havrysh.github.io/layout_product-cards/)
Текст "Купить" має бути весь в uppercase

<img width="449" alt="image" src="https://user-images.githubusercontent.com/66570142/159692461-129f4216-ab34-4634-9cb9-f99c83f64cc5.png">

2022-03-23 11:50 UTC, varseniuk commented on readme.md
> +- [TEST REPORT LINK](https://Havrysh.github.io/layout_product-cards/report/html_report/)
Тести не задеплоєні. Ти запускав команжу npm test перед деплоєм?

2022-03-23 11:50 UTC, varseniuk commented on src/index.html
> +    <p class="product-card__description">Моноблок APPLE A1419 iMac 27" Retina 5K (MNED2UA/A)</p>
```suggestion
    <h3 class="product-card__description">Моноблок APPLE A1419 iMac 27" Retina 5K (MNED2UA/A)</h3>
```
Це, швидше, заголовок

2022-03-23 11:50 UTC, varseniuk commented on src/style.css
> +
```suggestion
```

2022-03-23 11:50 UTC, varseniuk commented on src/style.css
> +}
```suggestion
    margin-left: 16px;
}
```

2022-03-23 11:50 UTC, varseniuk commented on src/index.html
> +      </a>
```suggestion
      <a
        href="#"
        class="product-card__button-buy"
        data-qa="hover"
      >
        Купить
      </a>
```

2022-03-23 11:50 UTC, varseniuk commented on src/style.css
> +}
```suggestion
    border: 1px solid #00ACDC;
}

```
Має бути один пустий рядок в кінці коду

2022-03-24 18:12 UTC, varseniuk requested changes
Зараз твоя робота суттєво відрізняється від дизайну. Багато відмінностей, що можна й побачити на провалених тестах.
- розмір зображення не такий
- заголовок картки розтягується на більше рядків, ніж потрібно
- сам розмір картки трохи відрізняється
- відрізняється напис на кнопці


https://user-images.githubusercontent.com/66570142/159982611-10b809ac-0e6a-4cb2-a3e7-6fd62d70b2ee.mov

2022-04-18 14:34 UTC, Bohdan-Maksymiuk approved these changes
потрібно ще оновити PR - перевірю

2024-12-11 13:42 UTC, closed without merging