Solution
mate-academy/layout_product-cards pull request #1289
Opened 2022-03-30 20:45 UTC by yelnikov-andrii

https://github.com/yelnikov-andrii/layout_product-cards

2022-04-01 07:46 UTC, SavMary commented on src/style.css
> +.card__img img {
You should use class instead `img` (checklist 1)

2022-04-01 07:58 UTC, SavMary commented on src/style.css
> +.card__description.bold {
You can use only one class without `bold`

2022-04-01 08:03 UTC, SavMary commented on src/style.css
> +.link:hover {
hover effect chenges card height

2022-04-01 08:04 UTC, SavMary commented on src/index.html
> +      <div class="card">
You can remove this card

2022-04-01 08:14 UTC, SavMary requested changes

2022-04-01 08:14 UTC, SavMary commented on src/index.html
> +      <div class="card">
You can remove this card

2022-04-01 08:14 UTC, SavMary commented on src/style.css
> +.card__description.bold {
You can use only one class without bold

2022-04-01 08:14 UTC, SavMary commented on src/style.css
> +.link:hover {
hover effect chenges card height

2022-04-01 08:14 UTC, SavMary commented on src/style.css
> +.card__img img {
You should use class instead img (checklist 1)

2022-04-04 13:13 UTC, Anna-Tkachenko requested changes

2022-04-04 13:13 UTC, Anna-Tkachenko commented on src/index.html
> +      <div class="container__card"
Don't create additional containers, card should be BEM block

2022-04-04 13:13 UTC, Anna-Tkachenko commented on src/index.html
> +        <img class="img container__card--img" src="./images/imac.jpeg" alt="image">
Don't create additional BEM blocks (img): only card and stars

2022-04-04 13:13 UTC, Anna-Tkachenko commented on src/index.html
> +          </div>
🔥

2022-04-04 13:13 UTC, Anna-Tkachenko commented on src/index.html
> +        </div>
Use semantic tags

2022-04-04 13:13 UTC, Anna-Tkachenko commented on src/index.html
> +            Купить
make it the element of card block

2022-04-05 14:07 UTC, Anna-Tkachenko commented on src/style.css
> +  width: 200px;
You can't set width to the BEM block
Create additional class to make this block the element of body

2022-04-05 14:08 UTC, Anna-Tkachenko commented on src/style.css
> +  width: 160px;
Set left and right padding = 3px for image and width = 100% to pass the tests

2022-04-05 14:09 UTC, Anna-Tkachenko commented on src/style.css
> +  justify-content: center;
You don't have any child elements in card__title, delete redundant styles

2022-04-05 14:10 UTC, Anna-Tkachenko commented on src/style.css
> +  margin-right: 4px;
Don't forget to remove margin for the last star

2022-04-05 16:18 UTC, Anna-Tkachenko requested changes
You didn't fix some changes
1) Add border to the card (check correct styles in figma)
2) You can't set width to the card BEM block, you should create page__card element for setting this styles
3) Add padding: 3px and width: 100% for image to pass tests
4) Remove border from the title
5) Check correct font-weight for 'Цена' text
6) You didn't add 400 and 700 font-weight for Roboto font

2022-04-06 12:11 UTC, Anna-Tkachenko approved these changes
Good job! 👍

2022-04-06 12:11 UTC, Anna-Tkachenko commented on src/index.html
> +      </span>
Fix indents
```suggestion
      <span class="card__code">
        Код товара: 195434
      </span>
```

2022-04-06 12:11 UTC, Anna-Tkachenko commented on src/index.html
> +      </div>
Don't create additional wrappers

2022-04-06 12:11 UTC, Anna-Tkachenko commented on src/style.css
> +  width: 200px;
You can't set width to the BEM block

2024-03-19 14:38 UTC, closed without merging