imac-card was created
mate-academy/layout_product-cards pull request #1292
Opened 2022-04-01 15:14 UTC by alexandra-protyanova

2022-04-02 05:39 UTC, ZUBOV-ILLIA approved these changes

2022-04-04 12:16 UTC, Anna-Tkachenko requested changes
Fix comments and test report link

2022-04-04 12:16 UTC, Anna-Tkachenko commented on src/index.html
> +      </div>
Check point 5 in checklist, you shouldn't create additional BEM blocks (only card and stars)

2022-04-04 12:16 UTC, Anna-Tkachenko commented on src/index.html
> +      </div>
Div is redundant here, set all styles to card__text element

2022-04-04 12:16 UTC, Anna-Tkachenko commented on src/index.html
> +      </div>
Same here, delete redundant div

2022-04-04 12:16 UTC, Anna-Tkachenko commented on src/index.html
> +      <div class="card__feedback feedback">
Don't create additional BEM blocks, only card and stars

2022-04-04 12:16 UTC, Anna-Tkachenko commented on src/index.html
> +        </div>
Don't create redundant div, you can set all styles for comment element
Make it the element of the card instead of separate block

2022-04-04 12:16 UTC, Anna-Tkachenko commented on src/index.html
> +      </div>
Fix class naming according to BEM

2022-04-04 12:16 UTC, Anna-Tkachenko commented on src/index.html
> +      </div>
Don't create additional div
Set all styles for card__button element and don't create additional button block

2022-04-04 12:16 UTC, Anna-Tkachenko commented on src/style.css
> +}
Will be better to set content image using <img> tag instead of background

2022-04-04 14:57 UTC, Anna-Tkachenko approved these changes
Good job! 👍 
Just small comments

2022-04-04 14:57 UTC, Anna-Tkachenko commented on src/style.css
> +  width: 200px;
You can't set width to BEM block

2022-04-04 14:57 UTC, Anna-Tkachenko commented on src/style.css
> +.button--hover:hover {
Modifier is redundant here, you can use only pseudo-class

2023-09-07 09:37 UTC, closed without merging