Product cards
mate-academy/layout_product-cards pull request #1321
Opened 2022-04-06 17:24 UTC by Alyona-Pisotska

https://Alyona-Pisotska/.github.io/layout_product-cards/
https://Alyona-Pisotska/.github.io/layout_product-cards/report/html_report/

2022-04-07 07:06 UTC, Bohdan-Maksymiuk requested changes
> Reuse stars block from [Stars task](https://github.com/mate-academy/layout_stars) and keep it operational. If you change stars--4 modifier to stars--2 or other - number of selected stars should change correctly.

2022-04-11 09:30 UTC, marina-tilniak requested changes

2022-04-11 09:30 UTC, marina-tilniak commented on src/index.html
> +        </div>
better use semantic tags, e.g. here you can use `<span> `or `<p>`

2022-04-11 09:30 UTC, marina-tilniak commented on src/index.html
> +        </div>
here you can use tag `<h1>`

2022-04-11 13:17 UTC, ArturErmolenko approved these changes

2025-05-07 11:39 UTC, closed without merging