Product cards done
mate-academy/layout_product-cards pull request #1327
Opened 2022-04-09 15:52 UTC by JeniaGaidukov

- [DEMO LINK](https://JeniaGaidukov.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://JeniaGaidukov.github.io/layout_product-cards/report/html_report/)

2022-04-11 12:24 UTC, marina-tilniak requested changes

2022-04-11 12:24 UTC, marina-tilniak commented on src/index.html
> +
```suggestion
```

2022-04-11 12:24 UTC, marina-tilniak commented on src/index.html
> +
there  shouldn't be empty line between parent and child tags

2022-04-11 12:24 UTC, marina-tilniak commented on src/index.html
> +        </div>
use semantic tag

2022-04-11 12:24 UTC, marina-tilniak commented on src/index.html
> +        </div>
same here, you can use `<p>`

2022-04-11 12:24 UTC, marina-tilniak commented on src/style.css
> +  --small-fonts: #616070;
when you call variable like that you expect it to set font-size, not a color

2022-04-11 12:24 UTC, marina-tilniak commented on src/style.css
> +}
```suggestion
.stars--1 .stars__star:nth-child(1),
.stars--2 .stars__star:nth-of-type(-n+2),
.stars--3 .stars__star:nth-of-type(-n+3),
.stars--4 .stars__star:nth-of-type(-n+4),
.stars--5 .stars__star:nth-of-type(-n+5) {
  background-image: url(images/star-active.svg);
}
```

2022-04-12 13:39 UTC, JeniaGaidukov commented on src/style.css
> +}
Виправив, перевірте будь-ласка, дякую)

2022-04-13 07:31 UTC, marina-tilniak requested changes

2022-04-13 07:31 UTC, marina-tilniak commented on src/index.html
> +        </p>
це більше схоже на заголовок

2022-04-13 07:31 UTC, marina-tilniak commented on src/index.html
>  </html>
```suggestion
  </body>
</html>
```

2022-04-13 07:31 UTC, marina-tilniak commented on src/index.html
>  </html>
There shouldn't be empty line between parent and child elements

2022-04-13 16:53 UTC, JeniaGaidukov commented on src/index.html
>  </html>
Виправив.

2022-04-22 06:54 UTC, Bohdan-Maksymiuk approved these changes

2022-04-23 09:40 UTC, closed without merging