Develop
mate-academy/layout_product-cards pull request #1331
Opened 2022-04-16 06:07 UTC by MaxShylo

- [DEMO LINK](https://MaxShylo.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://MaxShylo.github.io/layout_product-cards/report/html_report/)

2022-04-18 12:18 UTC, aliceblunt8 requested changes

2022-04-18 12:18 UTC, aliceblunt8 commented on src/style.css
> +  padding: 32px 0 0;
add padding for all card's sides and remove paddings for all inner elements

2022-04-19 20:43 UTC, Bohdan-Maksymiuk requested changes
Good job 👍 
fix comments

2022-04-19 20:43 UTC, Bohdan-Maksymiuk commented on src/index.html
> +      <div class="product-card__ranking-container">
do you really need this div

2022-04-19 20:43 UTC, Bohdan-Maksymiuk commented on src/style.css
> +/* stylelint-disable block-no-empty */
it is not our way to hide mistakes

2022-04-19 20:43 UTC, Bohdan-Maksymiuk commented on src/style.css
> +/* stylelint-disable block-no-empty */
correct them

2022-04-21 10:29 UTC, Bohdan-Maksymiuk approved these changes

2022-09-18 10:54 UTC, closed without merging