Develop
mate-academy/layout_product-cards pull request #1336
Opened 2022-04-28 20:10 UTC by ABfeMate

- [DEMO LINK](https://ABfeMate.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://ABfeMate.github.io/layout_product-cards/report/html_report/)

2022-04-29 17:51 UTC, marina-tilniak requested changes

2022-04-29 17:51 UTC, marina-tilniak commented on src/style.css
> +  color: #00acdc;
don't duplicate code. Write here only styles that are different from .product-card__buy-button class

2022-04-29 17:51 UTC, marina-tilniak commented on src/style.css
> +  font-family: "Roboto", sans-serif;
you have same font-family for body, don't duplicate code

2022-04-29 17:51 UTC, marina-tilniak commented on src/index.html
> +    </div>
```suggestion
      </a>
    </div>
```
```suggestion
      </a>
    </div>
```

2022-05-05 11:16 UTC, Bohdan-Maksymiuk approved these changes

2024-04-22 13:31 UTC, closed without merging