Develop
mate-academy/layout_product-cards pull request #1350
Opened 2022-05-06 07:50 UTC by vitalii-labunskyi

- [DEMO LINK](https://vitalii-labunskyi.github.io/product-cards/)
- [TEST REPORT LINK](https://vitalii-labunskyi.github.io/product-cards/report/html_report/)

2022-05-06 08:25 UTC, ArtemTopolskyi requested changes

2022-05-06 08:25 UTC, ArtemTopolskyi commented on src/index.html
> +        КУПИТЬ
```suggestion
        Купить
```

2022-05-06 08:25 UTC, ArtemTopolskyi commented on src/style.css
> +  height: 406px;
не нужно хардкодить высоту карточки, она должна растягиваться, как ей необходимо

2022-05-06 08:25 UTC, ArtemTopolskyi commented on src/style.css
> +  width: 198px;
```suggestion
  width: 200px;
```
and use box-sizing: border-box

2022-05-06 08:25 UTC, ArtemTopolskyi commented on src/style.css
> +/* #region stars */
don't left comments in code

2022-05-06 14:22 UTC, aliceblunt8 commented on src/index.html
> +      </div>
use h2

2022-05-06 14:22 UTC, aliceblunt8 commented on src/index.html
> +      </div>
use p

2022-05-06 14:22 UTC, aliceblunt8 commented on src/index.html
> +      </div>
use p

2022-05-06 14:22 UTC, aliceblunt8 commented on src/style.css
> +.card {
remove padding from each element inside the card and add padding for all sides for container

2022-05-06 17:27 UTC, vitalii-labunskyi commented
done ))

2022-05-10 09:58 UTC, ArturErmolenko approved these changes

2022-05-17 14:16 UTC, closed without merging