add card
mate-academy/layout_product-cards pull request #1354
Opened 2022-05-06 15:45 UTC by Pavlo000

- [DEMO LINK](https://Pavlo000.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://Pavlo000.github.io/layout_product-cards/report/html_report/)

2022-05-10 10:57 UTC, Andriy3323 commented on src/index.html
> +          ">
<meta 
  name="viewport"
  content="
    width=device-width,
    user-scalable=no,
    initial-scale=1.0,
    maximum-scale=1.0,
    minimum-scale=1.0
  "
>

recommended

2022-05-10 11:23 UTC, Andriy3323 requested changes
Виправ незначні помилки👍

2022-05-10 11:23 UTC, Andriy3323 commented on src/index.html
> +          ">
```suggestion
    <meta
      name="viewport"
      content="
        width=device-width,
        user-scalable=no,
        initial-scale=1.0,
        maximum-scale=1.0,
        minimum-scale=1.0
      "
    >
```

2022-05-10 11:23 UTC, Andriy3323 commented on src/index.html
> +        alt="items"
В атрибув альт рекомендовано додавати логічний параметр для користувачів з обмеженими можливостями, які користуються скрінрідерами. Наприклад alt="product image"

2022-05-10 11:23 UTC, Andriy3323 commented on src/index.html
> +      </h1>
Тег h1 використовується лише один раз на сторінці, доцільніше використовувати тег h2

2022-05-10 11:23 UTC, Andriy3323 commented on src/index.html
> +        </p>
Можна обійтись бег тегу p

2022-05-10 11:23 UTC, Andriy3323 commented on src/style.css
> +}
Не варто добавляти клас для html, він зустрічається лише один єдиний раз

2022-05-10 11:23 UTC, Andriy3323 commented on src/style.css
> +
body теж зустрічається лише один раз

2022-05-10 11:23 UTC, Andriy3323 commented on src/style.css
> +  margin: 0 3px 37px;
Нижній margin 40px

2022-05-10 11:23 UTC, Andriy3323 commented on src/style.css
> +  margin-bottom: 3.8px;
Не доцільно використовувати не круглі значення пікселів. Візьми значення з дизайну

2022-05-10 11:23 UTC, Andriy3323 commented on src/style.css
> +  margin-bottom: 17px;
У дизайні значення відступу 18px

2022-05-10 11:23 UTC, Andriy3323 commented on src/style.css
> +  margin-bottom: 23.5px;
Вкотре не правильний запис пікселів(лише цілі числа)

2022-05-10 11:23 UTC, Andriy3323 commented on src/style.css
> +}
Незрозумілий падінг
Такий колір використовується вдруге. Спробуй створити змінну

2022-05-10 11:23 UTC, Andriy3323 commented on src/style.css
> +  --link-height: 40px;
Змінні, як правило, оголошують на початку документу, щоб в будь-який зручний момент можна було змінити її без зайвого клопоту

2022-05-11 11:48 UTC, illiarerun requested changes
GJ, now let's work on some fixes:

2022-05-11 11:48 UTC, illiarerun commented on src/index.html
> +      <h2 class="title card__title">
[Checklist](https://github.com/mate-academy/layout_product-cards/blob/master/checklist.md) 5th item. Don't make too many BEM-blocks.

2022-05-11 11:48 UTC, illiarerun commented on src/index.html
> +      <p class="phrase card__phrase">Код товара: 195434</p>
same here

2022-05-11 11:48 UTC, illiarerun commented on src/index.html
> +      <div class="reviews card__reviews">
and here

2022-05-11 11:48 UTC, illiarerun commented on src/index.html
> +        <p class="phrase reviews__phrase">
and here

2022-05-11 11:48 UTC, illiarerun commented on src/index.html
> +        </h2>
and everywhere here

2022-05-11 11:48 UTC, illiarerun commented on src/style.css
> +  font-size: 10px;
move that to `normalize.css`

2022-05-11 11:48 UTC, illiarerun commented on src/style.css
> +.card {
[Checklist](https://github.com/mate-academy/layout_product-cards/blob/master/checklist.md) 10th item. Make separate files for each BEM-block

2022-05-11 11:48 UTC, illiarerun commented on src/style.css
> +.stars {
same here

2022-05-11 11:48 UTC, illiarerun commented on src/style.css
> +  line-height: 38px;
why do you change `line-height` on hover?

2022-05-11 11:48 UTC, illiarerun commented on src/style.css
> +  border-radius: 5px;
you have this in `card__link` class
```suggestion
```

2022-05-11 11:48 UTC, illiarerun commented on src/style.css
> +  margin: 0 3px 40px;
you can use `auto` here
```suggestion
  margin: 0 auto 40px;
```

2022-05-12 17:10 UTC, jstmpelowycz requested changes
Fix some issues, and you're done

2022-05-12 17:10 UTC, jstmpelowycz commented on src/index.html
> +      </div>
Not BEM, fix it

2022-05-12 17:10 UTC, jstmpelowycz commented on src/index.html
> +          КУПИТЬ
Use `text-transform`

2022-05-12 17:10 UTC, jstmpelowycz commented on src/styles/normalize.css
> +}
Combine this

2022-05-12 17:10 UTC, jstmpelowycz commented on src/styles/normalize.css
> +}
Also, that's more about resetting, not normalizing

2022-05-12 17:10 UTC, jstmpelowycz commented on src/styles/review.css
> +}
This one should be placed in the `card.css`

2022-05-13 07:41 UTC, illiarerun requested changes
Few fixes left:

2022-05-13 07:41 UTC, illiarerun commented on src/index.html
> +    </div>
add some blank lines between siblings, this code is hard to read

2022-05-13 07:41 UTC, illiarerun commented on src/style.css
> +/* k */
delete this entire file, what it's purpose?

2022-05-13 07:41 UTC, illiarerun commented on src/styles/card.css
> +/* stylelint-disable-next-line selector-list-comma-newline-after */
don't disable eslint rules
```suggestion
```

2022-05-13 07:41 UTC, illiarerun commented on src/styles/card.css
> +}
move that to `reset.css`

2022-05-13 07:41 UTC, illiarerun commented on src/index.html
> +          class="link"
that shouldn't be a block

2022-05-13 07:41 UTC, illiarerun commented on src/index.html
> +      <div class="card__link">
you don't need this wrapper
```suggestion
```

2022-05-13 15:46 UTC, illiarerun approved these changes

2024-11-26 17:46 UTC, closed without merging