Catalog v01
mate-academy/layout_product-cards pull request #1362
Opened 2022-05-08 14:10 UTC by leonid-levtseniuk

2022-05-10 17:27 UTC, ArturErmolenko requested changes
make deploy again please

2022-05-13 09:05 UTC, leonid-levtseniuk commented on readme.md
> +- [TEST REPORT LINK](https://leonid-levtseniuk.github.io/layout_product-cards/report/html_report/)
так, робив, але зараз ще раз задеплою

2022-05-13 12:33 UTC, marina-tilniak requested changes

2022-05-13 12:33 UTC, marina-tilniak commented on readme.md
> +- [TEST REPORT LINK](https://leonid-levtseniuk.github.io/layout_product-cards/report/html_report/)
встав робочі посилання на демо та на тести сюди ⏬ 
<img width="633" alt="image" src="https://user-images.githubusercontent.com/94261494/168283102-27f6c7c3-cf90-4ec7-8db8-fcacc26ed241.png">

2022-05-13 12:33 UTC, marina-tilniak commented on src/index.html
> +          <div class="stars-1"></div>
```suggestion
          <div class="stars__star"></div>
```

2022-05-13 12:33 UTC, marina-tilniak commented on src/index.html
> +          <div class="stars-1"></div>
задай один клас для цих div, а для стилізації використай nth-child

2022-05-13 14:55 UTC, leonid-levtseniuk commented on src/index.html
> +          <div class="stars-1"></div>
прикріпив посилання, але на тести чомусь так і не працює

2022-05-13 14:58 UTC, leonid-levtseniuk commented on src/index.html
> +          <div class="stars-1"></div>
<img width="1680" alt="Знімок екрана 2022-05-13 о 17 58 33" src="https://user-images.githubusercontent.com/104631433/168311226-6a904dce-e64c-481a-a5dc-7888ffaefc2d.png">

2022-05-13 19:27 UTC, marina-tilniak requested changes
старайся не задавати ширину та висоту явно коли у цьому немає необхідності, подумай де можна прибрати явно задану ширину
перезапусти ще раз тести, можливо запрацють

2022-05-13 19:27 UTC, marina-tilniak commented on src/index.html
> +        </div>
має бути можливість за допомогою модифікатора міняти кількість зірок

2022-05-13 19:27 UTC, marina-tilniak commented on src/style.css
> +  font-family: Roboto, Arial, Helvetica, sans-serif;
навіщо ще раз задавати font-family?

2022-05-13 19:27 UTC, marina-tilniak commented on src/style.css
> +  height: 406px;
ширина та висота мають визначатися контентом, не задавай їх явно

2022-05-13 19:27 UTC, marina-tilniak commented on src/style.css
> +  font-family: Roboto, Arial, Helvetica, sans-serif;
шрифт уже заданий для всієї сторінки

2022-05-13 19:27 UTC, marina-tilniak commented on src/style.css
> +  font-family: Roboto, Arial, Helvetica, sans-serif;
те саме

2022-05-15 15:52 UTC, leonid-levtseniuk commented
Тести всі пройшли, проблему з зірочками я незнаю як написати по-іншому, так само і в завданні з блоком зірочок
Другий тиждень вже то мучаю і не йде, вийшло зробити так, як в останньому коміті, якщо це невірно, то прошу допомоги і пояснення, як його можна зробити по-іншому, будь-ласка.
дякую
<img width="1680" alt="Знімок екрана 2022-05-15 о 18 49 45" src="https://user-images.githubusercontent.com/104631433/168481746-c8ff0327-865e-4323-8a1a-4501c6734841.png">

2022-05-17 10:47 UTC, Bohdan-Maksymiuk commented
якщо щось не зрозуміло з коментарів ментора - запитуй в своєму каналі і тегай

2022-05-17 10:50 UTC, ArtemTopolskyi requested changes

2022-05-17 10:50 UTC, ArtemTopolskyi commented on src/index.html
> +        <div class="card__amount">
используй семантические теги, для текста больше подходят <p>, а не <div>

2022-05-17 10:50 UTC, ArtemTopolskyi commented on src/style.css
> +  /* align-items: center; */
не оставляй комментариев в коде

2022-05-17 10:50 UTC, ArtemTopolskyi commented on src/style.css
> +  box-sizing: border-box;
это свойство можно вынести в общий селектор *

2022-05-17 10:50 UTC, Bohdan-Maksymiuk requested changes
```
.stars {
  display: flex;
}

.stars__star {
  height: 16px;
  width: 16px;
  background: url(/images/star.svg) no-repeat center;
  margin-right: 4px;
}

.stars--1 .stars__star:nth-child(-n+1),
.stars--2 .stars__star:nth-child(-n+2),
.stars--3 .stars__star:nth-child(-n+3),
.stars--4 .stars__star:nth-child(-n+4),
.stars--5 .stars__star:nth-child(-n+5) {
  background-image: url(/images/star-active.svg);
}
```

2022-05-17 10:50 UTC, Bohdan-Maksymiuk commented on src/index.html
> +        <div class="card__stars">
```suggestion
        <div class="card__stars stars stars--4">
```

2022-05-17 10:50 UTC, Bohdan-Maksymiuk commented on src/index.html
> +          <div class="card__stars"></div>
```suggestion
          <div class="stars__star"></div>
```
it is separate block

2022-05-18 14:01 UTC, ArtemTopolskyi approved these changes

2022-05-18 14:01 UTC, ArtemTopolskyi commented on src/index.html
> +        data-qa="hover">Купить</a>
```suggestion
        data-qa="hover"
      >
          Купить
        </a>
```

2022-05-18 15:35 UTC, closed without merging