Product card
mate-academy/layout_product-cards pull request #1363
Opened 2022-05-08 14:56 UTC by vsupruniuk

- [DEMO LINK](https://vsupruniuk.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://vsupruniuk.github.io/layout_product-cards/report/html_report/)

2022-05-10 09:53 UTC, k0nstrukt-or requested changes

2022-05-10 09:53 UTC, k0nstrukt-or commented on src/blocks/rating.css
> +  font-weight: 400;
це стандартне значення, можна і без нього

2022-05-10 09:53 UTC, k0nstrukt-or commented on src/blocks/text.css
> +  font-size: 12px;
ти вже задав розмір шрифта

2022-05-11 13:10 UTC, illiarerun commented on src/blocks/rating.css
> +  background-image: url(../images/star.svg);
all you need is to change `background-image` here

2022-05-11 13:10 UTC, illiarerun commented on src/blocks/card.css
> +  flex-shrink: 0;
redundant
```suggestion
```

2022-05-11 13:11 UTC, illiarerun commented on src/blocks/buy-link.css
> +  width: 100%;
redundant, block elemets will take up all of the available width
```suggestion
```

2022-05-11 13:12 UTC, illiarerun commented on src/blocks/buy-link.css
> +  height: 38px;
no, you should not change it here, use `box-sizing: border-box` so you wouldn't need to calculate it on hover
```suggestion
```

2022-05-12 16:15 UTC, jstmpelowycz commented on src/index.html
> +      crossorigin="anonymous">
Format code properly

2022-05-12 16:16 UTC, jstmpelowycz approved these changes
Good job 🔥

2024-01-12 12:32 UTC, closed without merging