product-card
mate-academy/layout_product-cards pull request #1492
Opened 2022-06-09 10:00 UTC by Kras4iy

- [DEMO LINK](https://Kras4iy.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://Kras4iy.github.io/layout_product-cards/report/html_report/)

I think that pixel perfect didnt pass because of **gap**

2022-06-09 11:14 UTC, solaryasha requested changes

2022-06-09 11:14 UTC, solaryasha commented on src/style.css
> +  /* align-items: center; */
Не залишай коментарі

2022-06-09 11:14 UTC, solaryasha commented on src/style.css
> +.card {
11 пункт чекліста - [master/checklist.md](https://github.com/mate-academy/layout_product-cards/blob/master/checklist.md)

2022-06-09 11:14 UTC, solaryasha commented on src/style.css
> +  width: 166px;
Картка 200 пікселів, тобі потрібно задати border-box, щоб не займатися зайвою математикою

2022-06-09 11:14 UTC, solaryasha commented on src/style.css
> +  flex-direction: row;
Дефолтне значення, можна явно і не вказувати

2022-06-09 11:14 UTC, solaryasha commented on src/style.css
> +  flex-basis: 100%;
Why do we need this ?

2022-06-09 11:14 UTC, solaryasha commented on src/style.css
> +  flex-basis: 100%;
Why do we need this ?

2022-06-09 11:14 UTC, solaryasha commented on src/style.css
> +  gap: 17px;
А чому саме 17, звідки взялося це число ?

2022-06-09 11:14 UTC, solaryasha commented on src/style.css
> +.stars {
11 пункт чекліста - [master/checklist.md](https://github.com/mate-academy/layout_product-cards/blob/master/checklist.md)

2022-06-09 11:14 UTC, solaryasha commented on src/style.css
> +  gap: 55px;
А чому саме 55px ? А якщо текст ціни зміниться ?

2022-06-09 11:14 UTC, solaryasha commented on src/style.css
> +  padding: 12px 56px 12px 55px;
Краще вже явно висоту вказати
І ширина кнопки буде 100% відсотків батьківського контейнера

2022-06-09 11:14 UTC, solaryasha commented on src/style.css
> +  border-radius: 5px;
Це значення не змінюється при ховері

2022-06-09 14:15 UTC, VETALEK requested changes
almost 💪

2022-06-09 15:16 UTC, VETALEK requested changes
Last charge 💪

2022-06-09 15:16 UTC, VETALEK commented on src/styles/card.css
> +  transition: color 0.4s linear;
you need both `color` and `background-color` transition 😉

2022-06-09 15:29 UTC, VETALEK approved these changes
Fire 🔥

2022-12-09 12:10 UTC, solaryasha approved these changes

2026-04-07 16:38 UTC, closed without merging