Initial
mate-academy/layout_product-cards pull request #1557
Opened 2022-06-25 15:35 UTC by MihailKostov

[DEMO LINK] https://MihailKostov.github.io/layout_product-cards/
[TEST REPORT LINK] https://MihailKostov.github.io/layout_product-cards/report/html_report/

2022-06-27 09:03 UTC, ArtemTopolskyi commented on src/styles/card.css
> +  position: absolute;
не нужно позиционировать все элементы абсолютом. Элементы должны быть статическими и позиционироваться  относительно других элементов в карточке

2022-06-27 09:03 UTC, ArtemTopolskyi commented on src/styles/card.css
> +  position: absolute;
аналогично

2022-06-27 09:04 UTC, ArtemTopolskyi requested changes
нужно избавиться от абсолютного позиционирования

2022-06-30 11:30 UTC, aliceblunt8 requested changes

2022-07-01 19:39 UTC, Bohdan-Maksymiuk approved these changes

2026-03-23 18:20 UTC, closed without merging