Solution
mate-academy/layout_product-cards pull request #1638
Opened 2022-07-18 11:36 UTC by oksana-kyryienko

- [DEMO LINK](https://oksana-kyryienko.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://oksana-kyryienko.github.io/layout_product-cards/report/html_report/)

2022-07-18 12:51 UTC, Githi54 commented on src/index.html
> +    <div class="container" data-qa="card">
Можливо можно було б дати назву, яка описує з яким блоком працюємо. Наприклад "card"

2022-07-18 12:53 UTC, Githi54 commented on src/index.html
> +        <p class="prices">Цена:</p>
Ціни в ціні?) Можно перейменувати

2022-07-18 12:56 UTC, Githi54 approved these changes
Дрібні недоліки, можливо суб'єктивні з мого боку))  В цілому, гарна робота👍

2022-07-19 04:12 UTC, dellachaise requested changes
Great start 👍 

Please change the code according to comments.

2022-07-19 04:12 UTC, dellachaise commented on src/index.html
> +    <div class="container" data-qa="card">
I agree, about changing the name to `card`.

2022-07-19 04:12 UTC, dellachaise commented on src/index.html
> +        <span class="suma">69 999 грн</span>
`prices` and  `suma` also should be `container__` elements

`container__prices`
`container__suma`

2022-07-19 04:12 UTC, dellachaise commented on src/index.html
> +      </div>
delete unnecessary wrappers and button - it's redundant.
```suggestion
        <a 
          data-qa="hover" 
          href="#"
          class="container__button"
        >
          Купить
        </a>
```

2022-07-19 05:12 UTC, dellachaise requested changes

2022-07-19 05:12 UTC, dellachaise commented on src/style.css
> +}
Add the possibility to change active stars to 1, 2 and so on, by changing modifier. Not only option for 4 should exist(you can take this code from `stars` task
![Screenshot 2022-07-19 at 08 12 23](https://user-images.githubusercontent.com/17098736/179670010-8fa7cf66-362a-439d-9402-79701d532c11.png)
.

2022-07-19 07:33 UTC, closed without merging