Completed tasks
mate-academy/layout_product-cards pull request #1833
Opened 2022-08-22 07:45 UTC by F-u-n-H-o-u-s-e

- [DEMO LINK](https://F-u-n-H-o-u-s-e.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://F-u-n-H-o-u-s-e.github.io/layout_moyo-header/report/html_report/)

2022-08-22 07:47 UTC, F-u-n-H-o-u-s-e commented
- [DEMO LINK](https://F-u-n-H-o-u-s-e.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://F-u-n-H-o-u-s-e.github.io/layout_product-cards/report/html_report/)

2022-08-26 09:18 UTC, liliia-livandovskaya commented on src/index.html
> +      >APPLE A1419 iMac 27" Retina 5K Monoblock (MNED2UA/A)</a>
```suggestion
      <a 
        href="#" 
        class="card__link"
      >
        APPLE A1419 iMac 27" Retina 5K Monoblock (MNED2UA/A)
      </a>
```

2022-08-26 09:19 UTC, liliia-livandovskaya commented on src/index.html
> +      >
```suggestion
      <img 
        src="images/imac.jpeg" 
        class="card__img"
        alt="iMac" 
      >
```
fix it all over your code

2022-08-26 09:53 UTC, liliia-livandovskaya commented on src/style.css
> +}
```suggestion
* {
  box-sizing: border-box;
}
```
in the `*` we can use only `box-sizing`

2022-08-26 09:54 UTC, liliia-livandovskaya commented on src/style.css
> +}
its better to set fonts in `html` selector

2022-08-26 09:54 UTC, liliia-livandovskaya commented on src/style.css
> +}
move it to the separate file

2022-08-26 09:56 UTC, liliia-livandovskaya commented on src/style.css
> +  font-family: Roboto-Bold, serif;
move the font-family to the `html` selector and use inherit if needed

2022-08-26 09:56 UTC, liliia-livandovskaya commented on src/style.css
> +  font-family: Roboto-Bold, sans-serif;
the same there

2022-08-26 09:57 UTC, liliia-livandovskaya commented on src/style.css
> +  font-family: Roboto-Normal, sans-serif;
move the `font-family` to the `html` selector and use inherit if needed

2022-08-26 09:58 UTC, liliia-livandovskaya requested changes
GJ! 👍  pay attention to the comments

2022-09-01 10:56 UTC, valerii-derkach requested changes

2022-09-01 10:56 UTC, valerii-derkach commented on src/styles/main.css
> +}
перенеси після імпорту

2022-09-01 10:56 UTC, valerii-derkach commented on src/styles/main.css
> +  height: 408px;
пункт 8 [чекліста](https://github.com/mate-academy/layout_product-cards/blob/master/checklist.md)

2023-02-09 08:27 UTC, closed without merging