moyo card first commit
mate-academy/layout_product-cards pull request #1883
Opened 2022-09-07 21:16 UTC by Denis-Sizemov

- [DEMO LINK](https://Denis-Sizemov.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://Denis-Sizemov.github.io/layout_product-cards/report/html_report/)

2022-09-08 10:27 UTC, alexandra-protyanova requested changes

2022-09-08 10:27 UTC, alexandra-protyanova commented on src/index.html
> +        >
```suggestion
      <a
        href="#"
        class="card__button"
        data-qa="hover"
      >
```

2022-09-08 10:27 UTC, alexandra-protyanova commented on src/index.html
> +      <div class="card__rate">
use more semantic tags I see only divs

2022-09-08 10:27 UTC, alexandra-protyanova commented on src/style.css
> +  width: 200px;
don't set width to bem block

2022-10-17 12:27 UTC, alexandra-protyanova requested changes

2022-10-17 12:27 UTC, alexandra-protyanova commented on src/style.css
> +  width: 200px;
width is still here, need to fix

2022-10-17 12:27 UTC, alexandra-protyanova commented on src/style.css
> +  font-family: "Roboto", sans-serif;
move to `html` selector

2022-10-17 12:27 UTC, alexandra-protyanova commented on src/style.css
> +.stars {
create separate file for each bem block

2022-11-14 07:03 UTC, tetiana-ivanchenko requested changes
fix all comments

2022-11-20 21:29 UTC, closed without merging