iMac--product-card
mate-academy/layout_product-cards pull request #1997
Opened 2022-10-05 19:42 UTC by Mykola-Hadupiak

[DEMO LINK](https://Mykola-Hadupiak.github.io/layout_product-cards/)
[TEST REPORT LINK](https://Mykola-Hadupiak.github.io/layout_product-cards/report/html_report/)

2022-10-06 06:19 UTC, alexandra-protyanova requested changes

2022-10-06 18:05 UTC, SanyaBratashchuk requested changes
add all files

2022-10-06 18:05 UTC, SanyaBratashchuk commented on src/index.html
> +        <div class="stars card__stars-stars--4">
```suggestion
        <div class="stars stars--4">
```

2022-10-06 18:15 UTC, Mykola-Hadupiak commented on src/index.html
> +        <div class="stars card__stars-stars--4">
how i can do this?

2022-10-06 18:44 UTC, SanyaBratashchuk requested changes

2022-10-06 18:44 UTC, SanyaBratashchuk commented on src/styles/star.css
> +.card__stars-stars--5 :nth-child(-n + 5) {
```suggestion
.stars--1 :nth-child(-n + 1),
.stars--2 :nth-child(-n + 2),
.stars--3 :nth-child(-n + 3),
.stars--4 :nth-child(-n + 4),
.stars--5 :nth-child(-n + 5) {
```
You can do it like that)

2022-10-06 18:44 UTC, SanyaBratashchuk commented on src/styles/reset.css
> +}
```suggestion
body, p, h2 {
  margin: 0;
}

```

2022-10-06 18:44 UTC, SanyaBratashchuk commented on src/styles/star.css
> +}
```suggestion
}

```
And change file's name to stars

2022-10-06 18:44 UTC, SanyaBratashchuk commented on src/styles/reset.css
> +}
It is a good practice to leave one blank line in the end of the file

2022-10-06 18:44 UTC, SanyaBratashchuk commented on src/style.css
> +  margin-bottom: 4px;
Move card to the separate file card.scss

2022-10-07 11:28 UTC, alexandra-protyanova approved these changes
Well done!

2023-11-19 12:12 UTC, closed without merging