Develop
mate-academy/layout_product-cards pull request #2056
Opened 2022-10-27 12:59 UTC by Sergej161995

[DEMO LINK](https://Sergej161995.github.io/layout_product-cards/)
[TEST REPORT LINK](https://Sergej161995.github.io/layout_product-cards/report/html_report/)

2022-10-27 18:03 UTC, AlisaVlasova commented on src/index.html
> +        >
```suggestion
      <a
         class="card__buy"
         href="#"
         data-qa="hover"
       >
```

2022-10-27 18:03 UTC, AlisaVlasova commented on src/index.html
> +    </div>
```suggestion
      </a>
    </div>
```

2022-10-27 18:03 UTC, AlisaVlasova commented on src/style.css
> +  font-family: Roboto, sans-serif;
це краще в html селектор прописати

2022-10-27 18:03 UTC, AlisaVlasova commented on src/style.css
> +  padding: 0;
у боді нема дефолтних паддінгів

2022-10-27 18:03 UTC, AlisaVlasova commented on src/style.css
> +  box-sizing: border-box;
це можна в `*` перенести

2022-10-27 18:03 UTC, AlisaVlasova commented on src/style.css
> +  padding: 0 3px;
якщо це для центрування, то можна спробувати margin auto

2022-10-27 18:03 UTC, AlisaVlasova requested changes
Залишила комменти)

2022-10-28 07:46 UTC, Sergej161995 commented on src/style.css
> +  box-sizing: border-box;
@AlisaVlasova Добрый день, когда переношу в * все сбивается

2022-12-15 15:26 UTC, closed without merging