tests passed successfully
mate-academy/layout_product-cards pull request #2107
Opened 2022-11-04 11:10 UTC by read-my-code

[DEMO LINK](https://read-my-code.github.io/layout_product-cards/)
[TEST REPORT LINK](https://read-my-code.github.io/layout_product-cards/report/html_report/

2022-11-05 12:27 UTC, AlisaVlasova requested changes

2022-11-05 12:27 UTC, AlisaVlasova commented on src/index.html
> +        class="card_image"
```suggestion
        class="card__image" 
```

2022-11-05 12:27 UTC, AlisaVlasova commented on src/index.html
> +        <div class="stars stars--active">
```suggestion
        <div class="stars stars--4">
```

2022-11-05 12:27 UTC, AlisaVlasova commented on src/styles/blocks/card.css
> +  --card-elements-wirth: 166px;
не треба хардкодити всім внутрішнім елементам ширину, задай паддінги на саму картку, а елементи розтягни всередині

2022-11-05 12:27 UTC, AlisaVlasova commented on src/styles/blocks/card.css
> +}
це теж в card, page__card клас тут зайвий, в принципі

2022-11-05 12:27 UTC, AlisaVlasova commented on src/styles/blocks/stars.css
> +.stars--active :nth-child(-n+4) {
перенеси сюди класи з усіма модифікаторами із завдання з зірками, щоб можна було в девтулз змінити модифікатор і зірочки змінились відповідно

2022-11-05 12:27 UTC, AlisaVlasova commented on src/styles/index.css
> +  font-family: "Roboto", "Arial", sans-serif;
це краще в html селекторі задавати

2022-11-06 09:39 UTC, read-my-code commented on src/styles/index.css
> +  font-family: "Roboto", "Arial", sans-serif;
Але це ж є клас тега html. В чому проблема?

2022-11-06 14:59 UTC, ivanchuk-yurii approved these changes

2022-11-06 14:59 UTC, ivanchuk-yurii commented on src/index.html
> +        >
```suggestion
      <a 
        data-qa="hover" 
        class="card__button" 
        href="#"
      >
```

2022-11-06 14:59 UTC, ivanchuk-yurii commented on src/styles/blocks/card.css
> +  font-weight: 400;
it's default value, you don't need this. check in other places

2022-11-06 14:59 UTC, ivanchuk-yurii commented on src/styles/blocks/card.css
> +}
```suggestion
}

```
empty line on file ending

2022-11-06 18:05 UTC, closed without merging