Develop
mate-academy/layout_product-cards pull request #2215
Opened 2022-11-23 08:53 UTC by RomanHrytsiuk

https://RomanHrytsiuk.github.io/layout_product-cards/
https://RomanHrytsiuk.github.io/layout_product-cards/report/html_report/

2022-11-23 17:48 UTC, Viktor-Kost requested changes

2022-11-23 17:48 UTC, Viktor-Kost commented on src/index.html
> +      <div class="title">
This is redundant div wrapper
```suggestion

```

2022-11-23 17:48 UTC, Viktor-Kost commented on src/index.html
> +        <h2 class="title__name">
Please, check requirements and apply for the WHOLE document
There should be only 2 BEM blocks in your code card and stars all the others are just card elements

2022-11-23 17:48 UTC, Viktor-Kost commented on src/index.html
> +      </a>
```suggestion
      <a
         class="button"
         data-qa="hover"
         href="/">Buy
      </a>
```

2022-11-23 17:48 UTC, Viktor-Kost commented on src/index.html
> +      alt="APPLE IMac 27 Retina 5K Monoblock">
```suggestion
      <img
        class="card__image"
        src="./images/imac.jpeg"
        alt="APPLE IMac 27 Retina 5K Monoblock"
      >
```

2022-11-23 17:48 UTC, Viktor-Kost commented on src/style.css
> +@import "./styles/cardWithImage.css";
Please, use one case of naming files, naming styles etc [link](https://betterprogramming.pub/string-case-styles-camel-pascal-snake-and-kebab-case-981407998841)

2022-11-23 17:48 UTC, Viktor-Kost commented on src/style.css
> +  background-color: #00acdc;
Use variables for colors you use several times

2022-11-26 08:49 UTC, AlisaVlasova requested changes

2022-11-26 08:49 UTC, AlisaVlasova commented on src/index.html
> +        <p class="card-price__dollar">$2,199</p>
```suggestion
      <div class="card__price">
        <p class="card__price-text">Price:</p>
        <p class="card__price-dollar">$2,199</p>
```

2022-11-26 08:49 UTC, AlisaVlasova commented on src/index.html
> +        class="button"
```suggestion
        class="card__button"
```

2022-11-26 08:49 UTC, AlisaVlasova commented on src/style.css
> +  box-sizing: border-box;
move it to * selector

2022-11-26 08:49 UTC, AlisaVlasova commented on src/style.css
> +@import "./styles/blocks/stars.css";
add these files to git

2022-11-26 08:49 UTC, AlisaVlasova commented on src/style.css
> +}
move it to card block

2022-11-26 15:12 UTC, DarkMistyRoom requested changes
Your iMac looks a bit flattened
![image](https://user-images.githubusercontent.com/98764641/204095484-28b2b7c4-d349-4ae0-8195-f61cb3d0ed85.png)

You don't have to set so many margins for each element if you set paddings to the card container. Like here
![image](https://user-images.githubusercontent.com/98764641/204095566-0e5ea98c-7db6-446c-9fd3-db91ccbdf321.png)

2022-11-26 15:12 UTC, DarkMistyRoom commented on src/index.html
> +        href="/">Buy
```suggestion
        href="#">Buy
```

2022-11-26 15:12 UTC, DarkMistyRoom commented on src/index.html
> +        href="/">Buy
It shouldn't link to 404

2022-11-26 15:12 UTC, DarkMistyRoom commented on src/index.html
> +        alt="APPLE IMac 27 Retina 5K Monoblock">
```suggestion
      <img
        class="card__image"
        src="./images/imac.jpeg"
        alt="APPLE IMac 27 Retina 5K Monoblock"
      >
```

2022-11-26 15:12 UTC, DarkMistyRoom commented on src/index.html
> +        href="/">Buy
```suggestion
      <a
        class="card__button"
        data-qa="hover"
        href="/"
      >
        Buy
```

2022-11-26 15:12 UTC, DarkMistyRoom commented on src/blocks/stars.css
> +  margin: 0 16px 24px;
Don't set margins to a BEM block

2022-11-26 15:12 UTC, DarkMistyRoom commented on src/blocks/stars.css
> +}
It isn't a part of stars block

2022-11-27 11:15 UTC, SanyaBratashchuk requested changes

2022-11-27 11:15 UTC, SanyaBratashchuk commented on src/index.html
> +
```suggestion
    <div class="card__reviews">
      <div class="stars stars--4">
        <div class="stars__star"></div>
        <div class="stars__star"></div>
        <div class="stars__star"></div>
        <div class="stars__star"></div>
        <div class="stars__star"></div>
      </div>
      <div class="card__reviews-text">Review: 5</div>
   </div>
```
Make it work like that

2022-11-27 11:22 UTC, ivanchuk-yurii requested changes

2022-11-27 11:22 UTC, ivanchuk-yurii commented on src/blocks/card.css
> +  box-sizing: border-box;
you don't need this here, you already have this in  `*`

2022-11-27 11:22 UTC, ivanchuk-yurii commented on src/blocks/card.css
> +  font-weight: 400;
it's default value, remove, check in other places

2022-11-27 11:22 UTC, ivanchuk-yurii commented on src/blocks/stars.css
> +  background-image: url(../images/star.svg);
it's better to combine this into `background` property

2022-11-27 11:22 UTC, ivanchuk-yurii commented on src/style.css
> +h2 {
```suggestion
body,
p,
h2 {
```

2022-11-27 11:22 UTC, ivanchuk-yurii commented on src/index.html
> +
not fixed

2022-11-27 17:19 UTC, ivanchuk-yurii approved these changes

2024-06-21 20:31 UTC, closed without merging