product-card was created
mate-academy/layout_product-cards pull request #2292
Opened 2022-12-09 16:19 UTC by yaroslavna-horban

- [DEMO LINK](https://yaroslavna-horban.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://yaroslavna-horban.github.io/layout_product-cards/report/html_report/)

2022-12-09 16:33 UTC, Anton-Zhytonbaiev commented on src/index.html
> +
```suggestion
      <img 
        class="product-card__image" 
        src="images/imac.jpeg" 
        alt="Apple A1419 iMac 27$quot; Retina 5K Monoblock"
      >

```

2022-12-09 16:43 UTC, Anton-Zhytonbaiev commented on src/styles/blocks/product-card.css
> +  margin: 0 16px 4px;
also cheklist point 7 (maybe i wrong)

2022-12-09 16:48 UTC, Anton-Zhytonbaiev requested changes
Good job (i don't find smile, just imagine something good)

2022-12-09 16:56 UTC, yaroslavna-horban commented on src/styles/blocks/product-card.css
> +  margin: 32px 19px 40px;
I may be wrong but it isn't a block

2022-12-11 15:17 UTC, closed without merging

2022-12-12 10:01 UTC, alexandra-protyanova requested changes