beta version
mate-academy/layout_product-cards pull request #2293
Opened 2022-12-09 16:30 UTC by Anton-Zhytonbaiev

- [DEMO LINK](https://Anton-Zhytonbaiev.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://Anton-Zhytonbaiev.github.io/layout_product-cards/report/html_report/)

2022-12-09 16:53 UTC, vladyslav78292 requested changes

2022-12-09 16:53 UTC, vladyslav78292 commented on src/index.html
> +        </div>
checklist point 3

2022-12-09 16:53 UTC, vladyslav78292 commented on src/index.html
> +        alt="macImage"
checklist point 13

2022-12-09 16:53 UTC, vladyslav78292 commented on src/index.html
> +    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com"><link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&dis
would be better if you move second link to another row

2022-12-09 16:53 UTC, vladyslav78292 commented on src/index.html
> +        >
```suggestion
      <a
        href="#buy"
        class="card__buy buy"
        data-qa="hover"
      >
```

2022-12-09 16:53 UTC, vladyslav78292 commented on src/style.css
> +}
in this project should be 2 BEM blocks in your code - card and stars. create new folder inside src, for example "styles". in styles folder create files "card.css" and "stars.css". paste all code , which related with stars in stars.css and import it in this file. same with card block

2022-12-12 13:15 UTC, Denchepornyuk requested changes

2022-12-12 13:15 UTC, Denchepornyuk commented on src/index.html
> +    <div class="card" data-qa="card">
it's better to use article tag for the card

2022-12-12 13:15 UTC, Denchepornyuk commented on src/index.html
> +      </div>
it should be title, use tag for a title (h1, h2, h3, ...)

2022-12-12 13:15 UTC, Denchepornyuk commented on src/index.html
> +      </div>
don't use div for each element on the page, use more semantic tags

2022-12-12 13:15 UTC, Denchepornyuk commented on src/index.html
> +      </div>
the same, use semantic tags

2022-12-12 13:15 UTC, Denchepornyuk commented on src/index.html
> +          Buy
```suggestion
        Buy
```

2022-12-12 13:15 UTC, Denchepornyuk commented on src/index.html
> +      <div class="card__name name">
do you need `image` and `name` BEM blocks here?

2022-12-12 13:15 UTC, Denchepornyuk commented on src/index.html
> +      <div class="card__price price">
do you need block `price` here?

2022-12-12 13:15 UTC, Denchepornyuk commented on src/index.html
> +        <div class="number">
why just `number` it should be element from card

2022-12-12 13:15 UTC, Denchepornyuk commented on src/style.css
> +  font-family: Roboto, sans-serif;
add `font-family` to html tag

2022-12-12 15:33 UTC, Denchepornyuk approved these changes

2022-12-12 15:33 UTC, Denchepornyuk commented on src/style.css
> +  font-family: Roboto, sans-serif;
you can remove `font-family` from body, you have it in html tag

2024-01-05 10:10 UTC, closed without merging