card was created
mate-academy/layout_product-cards pull request #2367
Opened 2022-12-24 16:53 UTC by vanyachyzh

- [DEMO LINK](https://vanyachyzh.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://vanyachyzh.github.io/layout_product-cards/report/html_report/)

2022-12-25 10:19 UTC, nazarmatsevych requested changes
GJ, just small suggestions

2022-12-25 10:19 UTC, nazarmatsevych commented on src/styles/blocks/page.css
> +  font-family: Roboto, sans-serif;
move font-family to html selector

2022-12-25 10:19 UTC, nazarmatsevych commented on src/index.html
> +        Price:
dont put text into `div` tag, create another `p` tag instead

2022-12-25 10:19 UTC, nazarmatsevych commented on src/styles/blocks/card.css
> +  color: #616070;
move color to variable

2022-12-26 16:46 UTC, witflash requested changes
Overall all is great!
Please, do some minor fixes.

2022-12-26 16:46 UTC, witflash commented on src/index.html
> +      <a class="product-card__link" data-qa="hover">Buy</a>
```suggestion
      <p class="product-card__price-text">Price:</p>
      <p class="product-card__price-value">$2,199</p>
      <a class="product-card__link" data-qa="hover">Buy</a>
```

There is no need to use empty lines between single-line siblings.

2022-12-26 16:46 UTC, witflash commented on src/index.html
> +  </body>
```suggestion
    </div>
  </body>
```
There is no need to use an empty line between the child and the parent

2022-12-26 16:46 UTC, witflash commented on src/styles/blocks/page.css
> +  --gray: #616070;
Better to name them `--color-primary` and `--color-secondary` for example

2022-12-28 13:55 UTC, Viktor-Kost approved these changes
GJ!

2022-12-28 13:55 UTC, Viktor-Kost commented on src/index.html
> +    <div class="product-card" data-qa="card">
It's ok. But you can simplify the block naming and apply for other elements
```suggestion
    <div class="card" data-qa="card">
```

2024-03-07 18:46 UTC, closed without merging