Develop
mate-academy/layout_product-cards pull request #2391
Opened 2023-01-06 12:37 UTC by natalia-matash

- [DEMO LINK](https://natalia-matash.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://natalia-matash.github.io/layout_product-cards/report/html_report/)

2023-01-06 12:47 UTC, natalia-matash commented
I was faced  with a problem. Firtly, I didn't want to fix size of image, so I did this way, like in mockup:
.card__image {
  padding: 32px 19px 0;
  margin-bottom: 40px;
}
.card__img {
  max-width: 100%;
}
But, image didn't cover all block and I had 0.8px bottom backlash. I was trying object fit, coudn't help.
Same problem with max-height, height, weight.
So, I had fixed size of clock

2023-01-07 10:54 UTC, SanyaBratashchuk requested changes
button in hover state doesn't look like in mockup 
![image](https://user-images.githubusercontent.com/97547824/211146659-69d8a7db-4748-401b-8ed3-236249d386f0.png)

2023-01-08 11:20 UTC, SanyaBratashchuk approved these changes

2023-01-08 11:20 UTC, SanyaBratashchuk commented on src/styles/blocks/cards.css
> +.card {
rename this file cards.css  => card.css

2023-01-08 15:11 UTC, natalia-matash commented
Done

вс, 8 янв. 2023 г. в 13:20, Sasha Bratashchuk ***@***.***>:

> ***@***.**** approved this pull request.
> ------------------------------
>
> In src/styles/blocks/cards.css
> <https://github.com/mate-academy/layout_product-cards/pull/2391#discussion_r1064124775>
> :
>
> > @@ -0,0 +1,88 @@
> +.card {
>
> rename this file cards.css => card.css
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mate-academy/layout_product-cards/pull/2391#pullrequestreview-1239766668>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZ6IIDL4JAESM2HOVJTTLQDWRKPHTANCNFSM6AAAAAATTBFZKE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-02-01 12:02 UTC, closed without merging