commit with product card
mate-academy/layout_product-cards pull request #2394
Opened 2023-01-07 17:09 UTC by Faridun92

2023-01-08 12:15 UTC, SanyaBratashchuk requested changes
Your solution doesn't follow BEM. Please rewrite it. If you have any questions feel free to ask in Slack

2023-01-08 12:15 UTC, SanyaBratashchuk commented on src/index.html
> +          class="card__img card__img--margin-bottom"
```suggestion
          class="card__img "
```
You can apply margins directly to the BEM elements

2023-01-08 12:15 UTC, SanyaBratashchuk commented on src/index.html
> +        <div class="info-width">
![image](https://user-images.githubusercontent.com/97547824/211195367-cff0a3ac-034d-469e-86db-0eb34b55609b.png)

2023-01-08 12:15 UTC, SanyaBratashchuk commented on src/index.html
> +          <div class="rating rating--margin-bottom">
![image](https://user-images.githubusercontent.com/97547824/211195370-180013a0-9501-4d26-a3d2-35db8133f2c0.png)

2023-01-08 12:15 UTC, SanyaBratashchuk commented on src/index.html
> +          class="card__img card__img--margin-bottom"
Fix it everywhere

2023-01-08 12:15 UTC, SanyaBratashchuk commented on src/index.html
> +          <div class="rating rating--margin-bottom">
Fix it everywhere

2023-01-10 10:12 UTC, DarkMistyRoom requested changes
- use the smallest value for side padding to avoid this 

![image](https://user-images.githubusercontent.com/98764641/211521460-091cd5de-652f-4524-95db-e1c9f7fafb7e.png)

- Be consistent with your margins. Add only top or bottom, don't add both.

![image](https://user-images.githubusercontent.com/98764641/211521533-f5fdda7e-28bb-421b-9bed-e8aa81dbb385.png)

2023-01-10 10:12 UTC, DarkMistyRoom commented on src/index.html
> +          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
```suggestion
    <meta 
      name="viewport"
      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
    >
```

2023-01-10 10:12 UTC, DarkMistyRoom commented on src/index.html
> +        <img
```suggestion
      <div class="container__card card" data-qa="card">
        <img 
```

2023-01-10 10:12 UTC, DarkMistyRoom commented on src/index.html
> +            <p class="card__model">APPLE A1419 iMac 27" Retina 5K Monoblock (MNED2UA/A)</p>
```suggestion
            <h2 class="card__model">APPLE A1419 iMac 27" Retina 5K Monoblock (MNED2UA/A)</h2>
```

2023-01-10 10:12 UTC, DarkMistyRoom commented on src/index.html
> +            <div class="stars">
```suggestion
            <div class="stars stars--4">
```

2023-01-10 10:12 UTC, DarkMistyRoom commented on src/index.html
> +            data-qa="hover">
```suggestion
          <a 
            href="/buy" 
            class="card__buy-button card__buy-button--is-active" 
            data-qa="hover"
          >
```

2023-01-10 10:12 UTC, DarkMistyRoom commented on src/style.css
> +}
set `border-box` to the * selector, font-family to html, and inherit where needed. Not all of these elements have default margins and paddings. try to improve this section of code to make better performance

2023-01-12 15:45 UTC, Virass approved these changes

2026-08-18 22:33 UTC, closed without merging