solution
mate-academy/layout_product-cards pull request #2457
Opened 2023-01-25 13:22 UTC by milenadiamonds1

https://milenadiamonds1.github.io/layout_product-cards/

2023-01-27 14:15 UTC, vladyslav-mosor requested changes

2023-01-27 14:15 UTC, vladyslav-mosor commented on src/index.html
>          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
Please fix indentations for attributes. And string that has length over 80 should be wrapped

2023-01-27 14:15 UTC, vladyslav-mosor commented on src/index.html
> +      >
Please fix indentations

2023-01-27 14:15 UTC, vladyslav-mosor commented on src/index.html
> +      >
Please fix indentations

2023-01-27 14:15 UTC, vladyslav-mosor commented on src/styles/blocks/card.css
> +  height: 40px;
Don`t set height prop for link. Let the content dictate it

2023-01-27 14:15 UTC, vladyslav-mosor commented on src/styles/blocks/card.css
> +  border: var(--specificBlue);
```suggestion
  border-color: var(--specificBlue);
```

2023-01-27 14:16 UTC, vladyslav-mosor commented
Your link doesn`t have border on hover state as it shows on mockup.

2023-01-27 14:38 UTC, vladyslav-mosor approved these changes

2023-01-27 14:38 UTC, vladyslav-mosor commented on src/index.html
> +    >
![image](https://user-images.githubusercontent.com/121725856/215112333-018b88b6-0501-4004-8bcf-541f7b82ea48.png)

Fix like it shows at the example

2023-01-30 16:11 UTC, Andr1yK requested changes
why do u need all font weights?
<img width="312" alt="image" src="https://user-images.githubusercontent.com/86183007/215530351-a793d2a1-d0a7-44bf-8908-12a6f119a9d3.png">

2023-01-30 16:11 UTC, Andr1yK commented on src/index.html
> +    >
```suggestion
    <meta
    	name="viewport"
      content="
        width=device-width, 
        user-scalable=no, 
        initial-scale=1.0, 
        maximum-scale=1.0, 
        minimum-scale=1.0
      "
    >
```

2023-01-30 16:11 UTC, Andr1yK commented on src/styles/variables.css
> +}
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/86183007/215530843-bc9266f0-3b3e-46d5-911e-76bf474976c4.png">

2023-01-30 16:11 UTC, Andr1yK commented on src/styles/reset.css
> +}
```suggestion
body,
p {
  margin: 0;
}
```

2023-01-31 11:04 UTC, Andr1yK requested changes
Never add dist/build folders to PR, let's remove it
<img width="391" alt="image" src="https://user-images.githubusercontent.com/86183007/215743146-eb651a6b-05a1-42cd-9e5c-3bc023227777.png">

2023-01-31 11:09 UTC, Andr1yK requested changes
Do u use Roboto-Thin file?

2023-01-31 11:09 UTC, Andr1yK commented on src/styles/variables.css
> +  --borderColor: #f3f3f3;
what is basic?) is it a color, or maybe a size?

2023-01-31 11:09 UTC, Andr1yK commented on src/styles/variables.css
> +  --borderColor: #f3f3f3;
good practice for naming colors is a `--c` + `color name`
F.E: `--c-white`

2023-01-31 11:09 UTC, Andr1yK commented on src/styles/blocks/stars.css
> +
```suggestion
}

```

2023-01-31 11:09 UTC, Andr1yK commented on src/styles/blocks/stars.css
> +  background-image: url("/images/star.svg");
let's avoid too many nth-child, and set background-image as default for stars__star class

2023-01-31 11:09 UTC, Andr1yK commented on src/styles/blocks/card.css
> +}
```suggestion
}

```

2023-01-31 11:09 UTC, Andr1yK commented on src/index.html
> +    	name="viewport"
```suggestion
      name="viewport"
```

2023-01-31 13:43 UTC, closed without merging