created a simple product card
mate-academy/layout_product-cards pull request #2622
Opened 2023-02-24 13:04 UTC by Evgenb000

- [DEMO LINK](https://evgenb000.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://evgenb000.github.io/layout_product-cards/report/html_report/)

2023-02-27 14:53 UTC, BondarenkoDmitriy commented
Unfortunately, there is no way to check, because
https://prnt.sc/ROLEKj-mvQq8

2023-02-28 08:23 UTC, Evgenb000 commented
> Unfortunately, there is no way to check, because [prnt.sc/ROLEKj-mvQq8](https://prnt.sc/ROLEKj-mvQq8)
i made some changes, its gonna work

2023-02-28 14:21 UTC, VinnieJ-2k20 requested changes
Some small changes left.
Details in comments.

2023-02-28 14:21 UTC, VinnieJ-2k20 commented on src/blocks/blocks.css
> +  font-weight: 400;
This is default value.

2023-02-28 14:21 UTC, VinnieJ-2k20 commented on src/blocks/stars.css
> +}
This belongs in the different file.

2023-02-28 14:21 UTC, VinnieJ-2k20 commented on src/blocks/stars.css
> +.stars--4 .stars__star:nth-child(-n+4) {
Need to have all possible selectors here. See checklist.

2023-02-28 14:29 UTC, danylo-dobrovolskyi reviewed
everything looks good, but there is some problem with positioning of the stars, let the mentor take a look

2023-02-28 16:30 UTC, VinnieJ-2k20 approved these changes

2023-06-20 13:04 UTC, closed without merging