create product card
mate-academy/layout_product-cards pull request #2660
Opened 2023-02-25 22:34 UTC by kyatsenko

[DEMO LINK](https://kyatsenko.github.io/layout_product-cards/)
[TEST REPORT LINK](https://kyatsenko.github.io/layout_product-cards/report/html_report/)

The second test fails because it does not find the reference.

2023-02-28 12:16 UTC, closed without merging

2023-03-01 11:58 UTC, jstmpelowycz requested changes
awesome, almost done! let's take care of your code, see the comments below 👇

2023-03-01 11:58 UTC, jstmpelowycz commented on src/index.html
> +      <img
no spaces between non-siblings
```suggestion
  <body>
    <div class="card" data-qa="card">
      <img
```

2023-03-01 11:58 UTC, jstmpelowycz commented on src/index.html
> +        <div class="star card__rating">
> no spaces between non-siblings

same here

2023-03-01 11:58 UTC, jstmpelowycz commented on src/index.html
> +        <div class="star card__rating">
seems like you don't use `star` class, so you can remove it

2023-03-01 11:58 UTC, jstmpelowycz commented on src/index.html
> +      </div>
> no spaces between non-siblings
```suggestion
        </div>

        <div class="card__review">Reviews: 5</div>
      </div>
```

2023-03-01 11:58 UTC, jstmpelowycz commented on src/index.html
> +    </div>
2 points: proper formatting + no spaces between non-siblings
```suggestion
      <a
        class="card__button"
        href="#"
        data-qa="hover"
      >
        Buy
      </a>
    </div>
```

2023-03-01 11:58 UTC, jstmpelowycz commented on src/style.css
> +.card {
this particularly applies to it — the checklist, p. 11
let's split this styles into dedicated files

2023-03-01 11:58 UTC, jstmpelowycz commented on src/style.css
> +.stars {
the checklist, p.11

2023-03-01 11:58 UTC, jstmpelowycz commented on src/style.css
> +  height: 40px;
the checklist, p.8

2023-03-01 11:58 UTC, jstmpelowycz commented on src/style.css
> +  border: 1px solid var(--blue-color);
initially, should be transparent

2023-03-01 11:58 UTC, jstmpelowycz commented on src/style.css
> +  align-items: center;
flexbox is not for this purpose, it's useful when we have multiple items to arrange

2023-03-01 11:58 UTC, jstmpelowycz commented on src/style.css
> +  font-family: Roboto, Arial, Helvetica, sans-serif;
you already normalize it, don't you?

2023-03-01 11:58 UTC, jstmpelowycz commented on src/style.css
> +  margin: 0 0 4px;
let's reset margins above

2023-03-01 11:58 UTC, jstmpelowycz commented on src/style.css
> +  display: block;
do you need it?

2023-03-01 11:58 UTC, jstmpelowycz commented on src/style.css
> +  flex-direction: row;
it's the default value

2023-03-01 11:58 UTC, jstmpelowycz commented on src/style.css
> +  --text-light-color: #616070;
I'd put it to `:root`

2023-03-06 07:45 UTC, SerhiiKirik approved these changes
Well done 🔥 
Let's check the comments & move on 👩‍💻

2023-03-06 07:45 UTC, SerhiiKirik commented on src/index.html
> +      </a>
```suggestion
      <a
        class="card__button"
        href="#"
        data-qa="hover"
      >
        Buy
      </a>
```

2023-03-06 07:45 UTC, SerhiiKirik commented on src/card.css
> +  padding: 11px 0;
Organize your styles 
I recommend you take a look at these styles code and use it in the feature
[9elements](https://9elements.com/css-rule-order) or [htmlAcademy](https://codeguide.academy/html-css.html#css-order)

2023-03-06 07:45 UTC, SerhiiKirik commented on src/card.css
> +  color: #fff;
Create variables for all colors)
```suggestion
  color: var(--color-white);
```