add product card
mate-academy/layout_product-cards pull request #2792
Opened 2023-03-22 18:59 UTC by MartaChobaniuk

- [DEMO LINK](https://martachobaniuk.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://martachobaniuk.github.io/layout_product-cards/report/html_report/)

2023-03-22 19:18 UTC, Volodymyr-Melnyk-Fron10der requested changes
Hi! Good job👍

1. Check backstop report, there are some inconsistences

2023-03-22 19:18 UTC, Volodymyr-Melnyk-Fron10der commented on src/index.html
> +        </a>
```suggestion
        <a
          href="#"
          class="product-card__button"
          data-qa="hover"
        >
          Buy
        </a>
```

2023-03-22 19:18 UTC, Volodymyr-Melnyk-Fron10der commented on src/style.css
> +  border: 1px solid #f3f3f3;
so move all color if you do it for some of them

2023-03-22 19:18 UTC, Volodymyr-Melnyk-Fron10der commented on src/style.css
> +  font-family: "Roboto", Arial, Helvetica, sans-serif;
move font family into html selector

2023-03-22 19:18 UTC, Volodymyr-Melnyk-Fron10der commented on src/style.css
> +  font-style: normal;
remove redundant default properties

2023-03-23 15:47 UTC, loralevitska requested changes
Almost done) Let's fix tests. Try to use line-height for `product-card__rewiews`
Then switch between two tabs 
![image](https://user-images.githubusercontent.com/70009205/227258169-b26c4618-ca13-4b83-a773-9b2c6abff9a5.png)
Test - your solution
Reference - example

Check difference in tests and fix it
If you have any questions, please ask them in fe_chat and tag mentors. It will be faster, because your answers in GitHub will be visible to mentor only after you re-request review

2023-03-24 07:55 UTC, vlad-demchuk approved these changes
we don't require pixel perfect, however you could try to fix test with this styles for `product-card__rewiews`

```
line-height: 14px;
display: flex;
align-items: center;

2023-05-26 08:25 UTC, closed without merging