Product card 5.0
mate-academy/layout_product-cards pull request #2813
Opened 2023-03-29 13:59 UTC by Dimoshua

- [DEMO LINK](https://Dimoshua.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://Dimoshua.github.io/layout_product-cards/report/html_report/)

2023-03-29 18:34 UTC, Volodymyr-Melnyk-Fron10der requested changes
Almost there!

2023-03-29 18:34 UTC, Volodymyr-Melnyk-Fron10der commented on src/style.css
> +.card {
move into separated file

2023-03-29 18:34 UTC, Volodymyr-Melnyk-Fron10der commented on src/style.css
> +}
you can move it into normalize.css

2023-03-29 18:34 UTC, Volodymyr-Melnyk-Fron10der commented on src/style.css
> +  line-height: 14px;
it's not a common rules, remove it from the html selector and set only where you really need it

2023-03-29 18:34 UTC, Volodymyr-Melnyk-Fron10der commented on src/style.css
> +.card__buy {
add some transition to the button

2023-03-29 18:34 UTC, Volodymyr-Melnyk-Fron10der commented on src/style.css
> +  height: 40px;
do not hardcode height, use paddings

2023-03-30 06:59 UTC, Dimoshua commented on src/style.css
> +.card__buy {
for example: transition: 2s;
???

2023-03-30 07:07 UTC, closed without merging