add task solution
mate-academy/layout_product-cards pull request #2868
Opened 2023-04-13 15:29 UTC by NickMitchell61

- [DEMO LINK](https://NickMitchell61.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://NickMitchell61.github.io/layout_product-cards/report/html_report/)

2023-04-19 12:59 UTC, naziamoff requested changes
already great, but let's make it perfect

2023-04-19 12:59 UTC, naziamoff commented on src/index.html
> +
no need to add empty line between head and body
```suggestion
```

2023-04-19 12:59 UTC, naziamoff commented on src/index.html
> +        >
don't forget about the indents between elements of different nesting levels
```suggestion
        <a
          href="#"
          data-qa="hover"
          class="card__button"
        >
```

2023-04-19 12:59 UTC, naziamoff commented on src/styles/blocks/card.css
> +}
you can just add it to card and it will be inherited

2023-04-19 12:59 UTC, naziamoff commented on src/styles/blocks/card.css
> +}
🔥 🔥

2023-04-20 05:59 UTC, vakopov reviewed
👌🏽

2023-04-20 05:59 UTC, vakopov commented on src/styles/utils/reset.css
> +h6 {
good job

2023-04-20 05:59 UTC, vakopov commented on src/styles/utils/reset.css
> +  list-style: none;
nothing to add

2023-04-20 05:59 UTC, vakopov approved these changes

2023-07-05 07:02 UTC, closed without merging