add card task
mate-academy/layout_product-cards pull request #2889
Opened 2023-04-18 13:22 UTC by vassavka

https://vassavka.github.io/layout_product-cards/
https://vassavka.github.io/layout_product-cards/report/html_report/

2023-04-18 14:02 UTC, nazarmatsevych requested changes
Looks very good,
left minor comments

2023-04-18 14:02 UTC, nazarmatsevych commented on src/styles/blocks/card.css
> +  margin: 0 auto 40px;
You can add align-items: center rule to your card to avoid adding margin: 0 auto to each card element

2023-04-18 14:02 UTC, nazarmatsevych commented on src/styles/blocks/card.css
> +  max-width: 200px;
```suggestion
  width: 200px;
```

card should always have 200px width

2023-04-19 08:42 UTC, vassavka commented
vassavka.github.io/layout_product-cards/
vassavka.github.io/layout_product-cards/report/html_report/

2023-04-19 09:41 UTC, DarkMistyRoom requested changes
Great. Just fix the button hover behavior
It would be good to move these files to the `utils` folder
![image](https://user-images.githubusercontent.com/98764641/233034385-df5451d6-ce82-4902-8b63-556d2e463ed8.png)

2023-04-19 09:41 UTC, DarkMistyRoom commented on src/styles/blocks/card.css
> +  border: 1px solid var(--main-color);
![image](https://user-images.githubusercontent.com/98764641/233034799-5a52d2b9-e76f-4a37-acb6-048ba087c0fa.png)

2023-04-19 13:30 UTC, vassavka commented
https://vassavka.github.io/layout_product-cards/
https://vassavka.github.io/layout_product-cards/report/html_report/

2023-04-19 14:11 UTC, mykhalenych approved these changes

2024-01-08 11:00 UTC, closed without merging