Develop
mate-academy/layout_product-cards pull request #2903
Opened 2023-04-20 16:10 UTC by andrii-petruk

2023-04-20 17:26 UTC, loralevitska requested changes
Please deploy your solution, and before review check demo_link. If you have any questions, please ask them in fe_chat and tag mentors. It will be faster, because your answers in GitHub will be visible to mentor only after you re-request review
![image](https://user-images.githubusercontent.com/70009205/233441723-1140108f-dfb2-42f0-9fb4-42202e8f549a.png)

2023-04-20 17:26 UTC, loralevitska commented on src/style.css
> +  border: 1px solid #f3f3f3;
It is a good practice to make all colors variable

2023-04-20 17:26 UTC, loralevitska commented on src/style.css
> +  font-style: normal;
Remove redundant default properties. Fix all cases if present

2023-04-20 17:26 UTC, loralevitska commented on src/style.css
> +  font-weight: 400;
Remove redundant default properties. Fix all cases if present

2023-04-20 17:26 UTC, loralevitska commented on src/index.html
> +      <div class="price-container">
Fit it 
![image](https://user-images.githubusercontent.com/70009205/233442319-47e1dffa-5338-418b-b085-99dbc75fac3a.png)

2023-04-23 08:07 UTC, SanyaBratashchuk requested changes

2023-04-23 08:07 UTC, SanyaBratashchuk commented on src/style.css
> +.card {
move each BEM block to the separate file

2023-04-23 08:07 UTC, SanyaBratashchuk commented on src/style.css
> +  border: 1px solid #f3f3f3;
movr color to the variable

2023-04-23 14:14 UTC, andrii-petruk commented on src/style.css
> +.card {
An error occurs when moving blocks to separate files 
"C:\Users\Asusr\projects\layout_product-cards\src\style.css:4:1: Failed to install stars.css.
  2 | 
  3 | @import url(card.css);
> 4 | @import url(stars.css);
    | ^
  5 | 
  6 | html {"
![Знімок екрана 2023-04-23 100908](https://user-images.githubusercontent.com/110127034/233844922-bdaeec79-19de-4fec-a80d-f4368a06eafe.png)

2023-04-23 17:24 UTC, closed without merging