product cards
mate-academy/layout_product-cards pull request #2991
Opened 2023-05-05 12:55 UTC by VChasnyk

- [DEMO LINK](https://VChasnyk.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://VChasnyk.github.io/layout_product-cards/report/html_report/)

2023-05-05 13:33 UTC, witflash requested changes
Well done! 👍 
Let's improve the syntax a little bit

2023-05-05 13:33 UTC, witflash commented on src/index.html
> +            BUY
You have too big indentation here (there have to be just 2 spaces)

2023-05-05 13:33 UTC, witflash commented on src/index.html
> +
There is no need to add an empty line between parent and child elements.

2023-05-05 13:33 UTC, witflash commented on src/index.html
> +
Use this approach just for siblings.

2023-05-05 13:33 UTC, witflash commented on src/style.css
> +  margin: 0  var(--min-margin-side) 24px;
Here is double space. It will work, but you have to use the correct syntax.

2023-05-05 13:33 UTC, witflash commented on src/style.css
> +  background: var(--color-button) ;
Remove a space before the semicolon

2023-05-05 13:33 UTC, witflash commented on src/style.css
> +.stars__container--4 > .stars__container-star:nth-child(n + 5) {
You don't need to use `>` (child combinator). It will work without it:
```
.stars__container--0 .stars__container-star,
etc.
```

2023-05-06 17:47 UTC, agniya-i approved these changes

2023-05-06 17:47 UTC, agniya-i commented on src/style.css
> +  margin: 0  var(--min-margin-side) 24px;
```suggestion
  margin: 0 var(--min-margin-side) 24px;
```

2023-05-06 17:47 UTC, agniya-i commented on src/index.html
> +        </a>
```suggestion
        <a
          class="card__link-buy"
          href="/"
          data-qa="hover"
        >
          BUY
        </a>
```

2023-05-28 16:12 UTC, closed without merging