add task solution
mate-academy/layout_product-cards pull request #3003
Opened 2023-05-08 10:35 UTC by RuslanSky23

2023-05-08 11:38 UTC, nazarmatsevych requested changes
Good work,
pls check comments and proofread your code with [checklist](https://github.com/mate-academy/layout_product-cards/blob/master/checklist.md)

2023-05-08 11:38 UTC, nazarmatsevych commented on src/style.css
> +}
It is not necessary to set max-height, remove this line

2023-05-08 11:38 UTC, nazarmatsevych commented on src/style.css
> +  max-width: 199px;
Change max-width to 200px and add box-sizing: border-box; rule, as the task description mentions the card width should be 200px including border

2023-05-08 11:38 UTC, nazarmatsevych commented on src/style.css
> +}
![image](https://user-images.githubusercontent.com/80700247/236810809-58480b4e-0fa3-4d54-862c-127865797cec.png)

2023-05-08 11:38 UTC, nazarmatsevych commented on src/style.css
> +  margin-bottom: 4px;
```suggestion
  margin: 40px 16px 4px;
```

replace with margin shorthand

2023-05-08 11:38 UTC, nazarmatsevych commented on src/style.css
> +  margin-right: 19px;
Add padding to whole card instead of margins to each element

2023-05-08 11:38 UTC, nazarmatsevych commented on src/style.css
> +  margin-left: 0.5px;
I think you can add background-position: center rule and remove this margin and backgrouind-size rules

2023-05-08 11:38 UTC, nazarmatsevych commented on src/style.css
> +  margin-left: 0.5px;
I think you can add background-position: center rule and remove this margin and backgrouind-size rules

2023-05-08 11:38 UTC, nazarmatsevych commented on src/style.css
> +  border-color: #00acdc;
Move repeatable colors to variables

2023-05-08 11:38 UTC, nazarmatsevych commented on src/style.css
> +  width: 166px;
Add padding to whole card and set width to 100%

2023-05-08 11:38 UTC, nazarmatsevych requested changes
Good work,
pls check comments and proofread your code with [checklist](https://github.com/mate-academy/layout_product-cards/blob/master/checklist.md)

2023-05-10 06:39 UTC, vlad-demchuk requested changes
test

2023-05-10 06:58 UTC, RuslanSky23 commented
https://RuslanSky23.github.io/layout_product-cards/

2023-05-10 08:06 UTC, vlad-demchuk commented on src/style.css
> +  border: 1px solid #00acdc;
move repeatable colors to variables

2023-05-10 11:22 UTC, anstsot approved these changes
Good job, approved!

2023-05-10 11:22 UTC, anstsot commented on src/index.html
> +        </a>
fix the code style
```suggestion
        <a
          href="#"
          class="card__link"
          data-qa="hover"
        >
          Buy
        </a>
```

2023-05-10 11:22 UTC, anstsot commented on src/index.html
> +          class="card__image-img">
```suggestion
          class="card__image-img"
        >
```

2023-05-25 09:56 UTC, closed without merging