Develop
mate-academy/layout_product-cards pull request #3037
Opened 2023-05-17 09:48 UTC by ABahatiy

https://abahatiy.github.io/layout_product-cards/ 
https://abahatiy.github.io/layout_product-cards/report/html_report/

2023-05-17 12:25 UTC, anstsot requested changes
It’s almost done! Let’s improve a little

2023-05-17 12:25 UTC, anstsot commented on src/stars.css
> +.card__stars {
it should be separate BEM block `stars`
```suggestion
.stars {
```

2023-05-17 12:25 UTC, anstsot commented on src/style.css
> +.card {
create separate `card` css file
![image](https://github.com/mate-academy/layout_product-cards/assets/22824431/e61c700c-5262-46f7-b7ea-
9cd30f5d43bf)

2023-05-17 12:46 UTC, ABahatiy commented
Thank you for review. Please check a new changes

2023-05-17 13:06 UTC, IvanFesenko requested changes
Check my comments

2023-05-17 13:06 UTC, IvanFesenko commented on src/card.css
> +  box-sizing: border-box;
move box-sizing into `*` selector

2023-05-17 13:06 UTC, IvanFesenko commented on src/card.css
> +  font-weight: 400;
font-weight by default is 400 - redudant. 
Fix all similar cases

2023-05-17 13:06 UTC, IvanFesenko commented on src/card.css
> +  font-size: 16px;
font-size by default is 16px - redudant too as well

2023-05-17 13:06 UTC, IvanFesenko commented on src/index.html
> +      <div class="card__code">Product code: 195434</div>
Use semantic tags for text content
h2-h5 for heading, p for other text

2023-05-18 07:15 UTC, etojeDenys approved these changes
lgtm

2023-05-21 08:45 UTC, closed without merging