Update readme.md
mate-academy/layout_product-cards pull request #3039
Opened 2023-05-17 12:02 UTC by YuriiHoliuk

2023-05-17 12:10 UTC, artemko123 approved these changes

2023-05-22 11:34 UTC, Broksus requested changes
test request

2023-05-22 11:36 UTC, Broksus approved these changes

2023-05-22 11:48 UTC, Broksus reviewed
test comment

2023-11-06 09:53 UTC, closed without merging