improved layout_product-cards
mate-academy/layout_product-cards pull request #3102
Opened 2023-05-27 10:22 UTC by a-kovalov

- [DEMO LINK](https://a-kovalov.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://a-kovalov.github.io/layout_product-cards/report/html_report/)

2023-05-29 06:52 UTC, etojeDenys requested changes

2023-05-29 06:52 UTC, etojeDenys commented on src/styles/blocks/card.scss
> +    margin-left: 22px;
why do you need this

2023-05-29 06:52 UTC, etojeDenys commented on src/styles/blocks/card.scss
> +  }
i think it's redundant

2023-05-29 07:55 UTC, a-kovalov commented
- [DEMO LINK](https://a-kovalov.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://a-kovalov.github.io/layout_product-cards/report/html_report/)

2023-05-30 06:29 UTC, etojeDenys approved these changes
lgtm

2023-05-30 06:44 UTC, closed without merging