completed task
mate-academy/layout_product-cards pull request #3504
Opened 2023-08-20 12:37 UTC by TKuts

- [DEMO LINK](https://TKuts.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://TKuts.github.io/layout_product-cards/report/html_report/)

2023-08-21 06:54 UTC, maxim2310 requested changes
Good work, try to make fixes and pass the tests

2023-08-21 06:54 UTC, maxim2310 commented on src/styles/card.scss
> +  &__img {
```suggestion
  padding: 32px 16px 16px;
  
  &__img {
```

2023-08-21 06:54 UTC, maxim2310 commented on src/styles/card.scss
> +  flex-direction: column;
add here align-items: center, because now your img is not centered

2023-08-21 06:54 UTC, maxim2310 commented on src/styles/card.scss
> +  max-width: 200px;
```suggestion
  width: 200px;
```

2023-08-21 06:54 UTC, maxim2310 commented on src/styles/card.scss
> +    font-weight: 400;
must be like default

2023-08-21 06:54 UTC, maxim2310 commented on src/styles/card.scss
> +    background-color: #00acdc;
also make variable for this color and try to set up right height for button, i think it will fix some test

2023-08-21 06:54 UTC, maxim2310 commented on src/styles/card.scss
> +  box-sizing: border-box;
also move it to reset file

2023-08-21 18:49 UTC, anastasiia-tilikina requested changes
I see changes in your code but they're not applied in your demo.
Did you forget to re-run `npm run deploy` ?

2023-08-22 07:31 UTC, lerastarynets approved these changes
You've got this, keep pushing forward!

2023-08-26 10:25 UTC, closed without merging