add cards task
mate-academy/layout_product-cards pull request #3535
Opened 2023-08-28 16:02 UTC by AnoriFrell

[DEMO LINK](https://AnoriFrell.github.io/layout_product-cards/)
 [TEST REPORT LINK](https://AnoriFrell.github.io/layout_product-cards/report/html_report/)

2023-08-28 16:05 UTC, lerastarynets requested changes
Pls try to pass all tests from backstop before asking for review again)

2023-08-29 09:24 UTC, volodymyr-soltys97 requested changes
This part of the task is incomplete
<img width="864" alt="image" src="https://github.com/mate-academy/layout_product-cards/assets/64750958/3fab2f18-4bb1-4dd1-b564-4e7460504efd">
<img width="1079" alt="image" src="https://github.com/mate-academy/layout_product-cards/assets/64750958/b71c7626-9b29-47fd-ab79-aa28426e583c">

2023-08-29 09:24 UTC, volodymyr-soltys97 commented on src/index.html
> +        >
Need to check and fix it everywhere
<img width="1074" alt="image" src="https://github.com/mate-academy/layout_product-cards/assets/64750958/f9fe1947-cc8c-4b27-9514-88204f295290">

2023-08-29 09:24 UTC, volodymyr-soltys97 commented on src/index.html
> +          data-qa="card">
```suggestion
      <div class="container__card card" data-qa="card">
```

2023-08-29 09:24 UTC, volodymyr-soltys97 commented on src/index.html
> +          Buy
```suggestion
        <a
          data-qa="hover"
          href="#"
          class="card__button button"
        >
          Buy
```

2023-08-29 09:24 UTC, volodymyr-soltys97 commented on src/styles/blocks/button.scss
> +    color: #00acdc;
Create a variables for repeating colors

2023-08-29 10:46 UTC, volodymyr-soltys97 commented on src/index.html
> +    >
```suggestion
    <link rel="preconnect" href="https://fonts.googleapis.com">
```

2023-08-29 10:46 UTC, volodymyr-soltys97 commented on src/styles/blocks/button.scss
> +    color: #00acdc;
Still not fixed

2023-08-30 07:07 UTC, volodymyr-soltys97 requested changes

2023-08-30 07:07 UTC, volodymyr-soltys97 commented on src/index.html
> +    >
Still not fixed from the previous review, need to fix it

2023-08-30 07:07 UTC, volodymyr-soltys97 commented on src/styles/blocks/button.scss
> +    color: #00acdc;
Use a variable here instead of hex format

2023-08-30 07:27 UTC, volodymyr-soltys97 approved these changes
Well done 🔥

2024-12-30 16:08 UTC, closed without merging