Develop
mate-academy/layout_product-cards pull request #3719
Opened 2023-10-18 14:17 UTC by mberezhna

- [DEMO LINK](https://mberezhna.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://mberezhna.github.io/layout_product-cards/report/html_report/)

2023-10-18 17:01 UTC, BudnikOleksii requested changes
Nice start, but a lot of requirements need to be done.
Check your solution in accordance with the task and the checklist before creating a pull request. 
❗️ Copy this Checklist to the Pull Request description after links, and put - [x] before each point after you checked it.
![image](https://github.com/mate-academy/layout_product-cards/assets/63243136/f6eba324-75c4-4398-9192-32b77f00b7da)

2023-10-19 07:01 UTC, mberezhna commented
- [DEMO LINK](https://mberezhna.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://mberezhna.github.io/layout_product-cards/report/html_report/)

- [+] there 2 BEM blocks `card` and `stars` each in it own file
- [+] SCSS Nesting is used for `elements`, `modifiers` and `pseudo-classes`
- [+] SCSS Variables are used for main values and placed in a **separate file**
- [+] all `stars--N` modifiers work as expected (Highlight first `N` stars)
- [+] Code follows all the [Code Style Rules ❗️](https://mate-academy.github.io/layout_task-guideline/html-css-code-style-rules)

2023-10-19 08:55 UTC, And678 requested changes
Almost done, one requirement to fix :)

2023-10-19 08:55 UTC, And678 commented on src/styles/blocks/stars.scss
> +  }
Requirement not implemented:
> all stars--N modifiers work as expected (Highlight first N stars)

2023-10-19 12:23 UTC, BudnikOleksii requested changes
Almost done, check the comments

2023-10-19 12:23 UTC, BudnikOleksii commented on src/index.html
> +        </a>
```suggestion
        <a
          href="#"
          class="button button--txt"
          data-qa="hover"
        >
          buy
        </a>
```
Don't forget about formatting

2023-10-19 12:23 UTC, BudnikOleksii commented on src/styles/blocks/stars.scss
> +    }
Still not implemented, if I change the modifier it's still 4 active stars:
- all stars--N modifiers work as expected (Highlight first N stars)

2023-10-19 12:23 UTC, BudnikOleksii commented on src/styles/blocks/normalize.scss
> +$button-activ: #fff;
Create a separate file for variables and move them to it

2023-10-19 12:23 UTC, BudnikOleksii commented on src/index.html
> +          <div class="stars">
Active stars should change depending on the modifier. For example, if I add the `stars--3` class it should be 3 active stars

2023-10-19 13:02 UTC, mberezhna commented
[DEMO LINK](https://mberezhna.github.io/layout_product-cards/)

[TEST REPORT LINK](https://mberezhna.github.io/layout_product-cards/report/html_report/)

[+] there 2 BEM blocks card and stars each in it own file

[+] SCSS Nesting is used for elements, modifiers and pseudo-classes

[+] SCSS Variables are used for main values and placed in a separate file

[+] all stars--N modifiers work as expected (Highlight first N stars)

[+] Code follows all the [Code Style Rules ❗️](https://mate-academy.github.io/layout_task-guideline/html-css-code-style-rules)

2023-10-19 15:03 UTC, BudnikOleksii approved these changes
Good job 👍

2023-10-19 15:03 UTC, BudnikOleksii commented on src/index.html
> +        >
```suggestion
        <a
          href="#"
          class="button button--txt"
          data-qa="hover"
        >
```
Don't forget about formatting

2024-03-08 08:16 UTC, closed without merging