add task solution
mate-academy/layout_product-cards pull request #3728
Opened 2023-10-18 19:00 UTC by ViktorAfk

- [DEMO LINK](https://ViktorAfk.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://ViktorAfk.github.io/layout_product-cards/report/html_report/)
- [x] there 2 BEM blocks `card` and `stars` each in it own file
- [x] SCSS Nesting is used for `elements`, `modifiers` and `pseudo-classes`
- [x] SCSS Variables are used for main values and placed in a **separate file**
- [x] all `stars--N` modifiers work as expected (Highlight first `N` stars)
- [x] Code follows all the [Code Style Rules ❗️

2023-10-18 19:02 UTC, ViktorAfk commented
I have a problem with a nesting class in stars.scss

2023-10-19 08:15 UTC, And678 requested changes
Looks very good but some requirements are not implemented yet. Feel free to join a QnA session if you are having any trouble.

2023-10-19 08:15 UTC, And678 commented on src/styles/blocks/card.scss
> +
```suggestion
```

2023-10-19 08:15 UTC, And678 commented on src/styles/blocks/card.scss
> +
Lots of extra newlines.

2023-10-19 08:15 UTC, And678 commented on src/index.html
> +        </div>
Stars should be a separate BEM block, as described in requirements.
```suggestion
        <div class="stars stars--active">
          <div class="stars__star"></div>
          <div class="stars__star"></div>
          <div class="stars__star"></div>
          <div class="stars__star"></div>
          <div class="stars__star"></div>
        </div>
```

2023-10-19 08:15 UTC, And678 commented on src/styles/blocks/stars.scss
> +}
Not done yet:
> all stars--N modifiers work as expected (Highlight first N stars)

2023-10-19 12:16 UTC, BudnikOleksii approved these changes
Nicely done 🚀

2023-10-19 12:18 UTC, closed without merging

2023-10-19 12:18 UTC, ViktorAfk commented
> Nicely done 🚀