Develop
mate-academy/layout_product-cards pull request #3817
Opened 2023-11-25 18:10 UTC by kapesha

- [DEMO LINK](https://kapesha.github.io/layout_product-cards/src)
- [TEST REPORT LINK](https://kapesha.github.io/layout_product-cards/src/report/html_report/)

X there 2 BEM blocks card and stars each in it own file
X SCSS Nesting is used for elements, modifiers and pseudo-classes
X SCSS Variables are used for main values and placed in a separate file
X all stars--N modifiers work as expected (Highlight first N stars)
X Code follows all the [Code Style Rules ❗️](https://mate-academy.github.io/layout_task-guideline/html-css-code-style-rules)

2023-11-25 19:26 UTC, VitaliyBodnar requested changes
Test report link is not valid, try to redeploy it.

2023-11-26 09:13 UTC, loralevitska requested changes
You have wrong links. Try to redeploy your solution 
Here should be your task solution, not task requirement 
![image](https://github.com/mate-academy/layout_product-cards/assets/70009205/f819f0bd-384d-44ea-8b65-b7089584142f)
and report link also doesn't work
![image](https://github.com/mate-academy/layout_product-cards/assets/70009205/0ae300a7-d6b9-4035-9ffe-28ad7d3f0b14)

If you have any questions, please ask them in fe_chat and tag mentors. It will be faster, because your answers in GitHub will be visible to mentor only after you re-request review

2023-11-26 09:13 UTC, loralevitska commented on src/index.html
> +            <div class="card__amount">$2,199</div>
Use `p` tag for this text

2023-11-26 09:13 UTC, loralevitska commented on src/index.html
> +          </a>
```suggestion
            data-qa="hover"
          >
            buy
          </a>
```

2023-11-26 09:13 UTC, loralevitska commented on src/index.html
> +            <div class="card__num-of-reviews">Reviews: 5</div>
Use `p` according semantic rules

2023-11-26 09:13 UTC, loralevitska commented on src/styles/blocks/card.scss
> +  border: 1px solid #F3F3F3;
It is a good practice to make all colors [variable](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties)

2023-11-26 09:13 UTC, loralevitska commented on src/styles/blocks/card.scss
> +  padding-bottom: 16px;
Combine with `padding` shorthand property. Fix all cases

2023-11-26 09:13 UTC, loralevitska commented on src/styles/blocks/card.scss
> +    font-weight: 400;
Remove redundant default value, fix all cases
```suggestion
```

2023-11-27 11:29 UTC, closed without merging