add task solution
mate-academy/layout_product-cards pull request #3847
Opened 2023-11-29 22:49 UTC by valentynavik

https://valentynavik.github.io/layout_product-cards/
https://valentynavik.github.io/layout_product-cards/report/html_report/

 `Checklist` to the `Pull Request`:
- [x] there 2 BEM blocks `card` and `stars` each in it own file
- [x] SCSS Nesting is used for `elements`, `modifiers` and `pseudo-classes`
- [x] SCSS Variables are used for main values and placed in a **separate file**
- [x] all `stars--N` modifiers work as expected (Highlight first `N` stars)
- [x] Code follows all the [Code Style Rules ❗️](https://mate-academy.github.io/layout_task-guideline/html-css-code-style-rules)

2023-11-30 08:52 UTC, volodymyr-soltys97 requested changes
Good job 👍 
Let's improve your code

2023-11-30 08:52 UTC, volodymyr-soltys97 commented on src/index.html
> +      rel="stylesheet">
```suggestion
    <link
      href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&family=Roboto:wght@400;500;700&display=swap"
      rel="stylesheet"
    >
```

2023-11-30 08:52 UTC, volodymyr-soltys97 commented on src/index.html
> +      <div class="card-code">Product code: 195434</div>
Use a semantic tag everywhere for text

2023-11-30 08:52 UTC, volodymyr-soltys97 commented on src/index.html
> +      </a>
```suggestion
      <a
        class="card-button"
        href="#"
        data-qa="hover"
      >
        Buy
      </a>
```

2023-11-30 08:52 UTC, volodymyr-soltys97 commented on src/styles/blocks/card.scss
> +  box-sizing: border-box;
Move box-sizing to the * selector

2023-11-30 08:52 UTC, volodymyr-soltys97 commented on src/styles/blocks/card.scss
> +    background-color: #00acdc;
Create a variable for this color and use it everywhere

2023-11-30 08:52 UTC, volodymyr-soltys97 commented on src/styles/blocks/stars.scss
> +.stars--1 .stars__star:nth-child(-n + 1),
```suggestion
}

.stars--1 .stars__star:nth-child(-n + 1),
```

2023-12-01 08:59 UTC, OleziO requested changes
![image](https://github.com/mate-academy/layout_product-cards/assets/56752562/e989b103-fd86-4f8b-a701-b6209a793726)
Fix demo link

2023-12-01 19:58 UTC, closed without merging