Add task solution
mate-academy/layout_product-cards pull request #4001
Opened 2024-01-21 20:32 UTC by Taras2552

- [DEMO LINK](https://Taras2552.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://Taras2552.github.io/layout_product-cards/report/html_report/)

- [ ] there 2 BEM blocks `card` and `stars` each in it own file
- [ ] SCSS Nesting is used for `elements`, `modifiers` and `pseudo-classes`
- [ ] SCSS Variables are used for main values and placed in a **separate file**
- [ ] all `stars--N` modifiers work as expected (Highlight first `N` stars)
- [ ] Code follows all the [Code Style Rules ❗️](https://mate-academy.github.io/layout_task-guideline/html-css-code-style-rules)

2024-01-22 08:02 UTC, volodymyr-soltys97 requested changes
Good job 👍 
Let's improve your code

2024-01-23 19:00 UTC, anastasiia-tilikina requested changes
please make sure that you've fixed all comments

2024-01-23 19:00 UTC, anastasiia-tilikina commented on src/index.html
> +      <div class="price">
price is not separate BEM block - it's an element of card. use proper class

2024-01-23 19:00 UTC, anastasiia-tilikina commented on src/index.html
> +      <div class="grade">
same here

2024-01-25 17:48 UTC, maxim2310 requested changes
check you demo link and request review again
![image](https://github.com/mate-academy/layout_product-cards/assets/96265844/a7e755d9-6221-4b4a-9973-e34ae3382013)

2024-01-25 18:31 UTC, loralevitska requested changes
Hi, I see you haven't fixed previous comments, maybe you did not push your changes? If you have any questions, please ask them in fe_chat and tag mentors. It will be faster, because your answers in GitHub will be visible to mentor only after you re-request review

2024-01-25 18:43 UTC, closed without merging

2024-01-25 18:43 UTC, Taras2552 commented
> Hi, I see you haven't fixed previous comments, maybe you did not push your changes? If you have any questions, please ask them in fe_chat and tag mentors. It will be faster, because your answers in GitHub will be visible to mentor only after you re-request review