result
mate-academy/layout_product-cards pull request #4006
Opened 2024-01-22 19:20 UTC by Andrew77788

- [DEMO LINK](https://Andrew77788.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://Andrew77788.github.io/layout_product-cards/report/html_report/)

2024-01-22 19:52 UTC, SanyaBratashchuk requested changes

2024-01-22 19:52 UTC, SanyaBratashchuk commented on src/styles/card.scss
> +  font-family: Roboto, sans-serif;
apply `font-family` for html tag selector 
```suggestion
```

2024-01-22 19:52 UTC, SanyaBratashchuk commented on src/styles/index.scss
> +
```suggestion
```

2024-01-22 19:52 UTC, SanyaBratashchuk commented on src/index.html
> +      </div>
use semantic tags like `h3`,  `p` for text

2024-01-23 07:52 UTC, etojeDenys approved these changes
good job

2024-01-23 07:52 UTC, etojeDenys commented on src/index.html
> +        </div>
better to use some semantic tags for the text

2024-08-13 13:58 UTC, closed without merging