add task solution
mate-academy/layout_product-cards pull request #4023
Opened 2024-01-26 12:37 UTC by Leh-02

- [DEMO LINK](https://Leh-02.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://Leh-02.github.io/layout_product-cards/report/html_report/)

- [x] there 2 BEM blocks `card` and `stars` each in it own file
- [x] SCSS Nesting is used for `elements`, `modifiers` and `pseudo-classes`
- [x] SCSS Variables are used for main values and placed in a **separate file**
- [x] all `stars--N` modifiers work as expected (Highlight first `N` stars)
- [x] Code follows all the [Code Style Rules ❗️](https://mate-academy.github.io/layout_task-guideline/html-css-code-style-rules)

2024-01-26 13:54 UTC, IvanFesenko requested changes
Reports page not available, Check my comments
![2024-01-26_15h48_48](https://github.com/mate-academy/layout_product-cards/assets/61904995/4ebe5966-86cc-448a-b99e-b913f578975b)

2024-01-26 13:54 UTC, IvanFesenko commented on src/index.html
> +      </div>
do not use div for text content - use semantic tags instead (h, p etc)

2024-01-26 13:54 UTC, IvanFesenko commented on src/index.html
> +      </div>
Stas should wokr with modifiers 1-5
```suggestion
      <div class="raiting">
        <div class="stars">
          <span class="stars__star"></span>
          <span class="stars__star"></span>
          <span class="stars__star"></span>
          <span class="stars__star"></span>
          <span class="stars__star"></span>
        </div>

        <p class="raiting__review">Reviews: 5</p>
      </div>
```

2024-01-26 13:54 UTC, IvanFesenko commented on src/index.html
> +      >buy</a>
```suggestion
      <a
        href="#"
        class="card__buy"
        data-qa="hover"
      >
        buy
      </a>
```

2024-01-26 13:54 UTC, IvanFesenko commented on src/styles/blocks/card.scss
> +  width: 198px;
```suggestion
  width: 200px;
```

2024-01-26 13:54 UTC, IvanFesenko commented on src/styles/blocks/card.scss
> +  height: 406px;
Do not hard code height
```suggestion

```

2024-01-26 13:54 UTC, IvanFesenko commented on src/styles/blocks/card.scss
> +    height: 36px;
```suggestion

```

2024-01-26 13:54 UTC, IvanFesenko commented on src/styles/blocks/card.scss
> +    font-family: Roboto, sans-serif;
move into `html` selector

2024-01-26 13:54 UTC, IvanFesenko commented on src/styles/blocks/card.scss
> +    font-family: Roboto, sans-serif;
```suggestion

```

2024-01-26 13:54 UTC, IvanFesenko commented on src/styles/blocks/card.scss
> +    font-weight: 400;
It's default values - redundant
```suggestion

```

2024-01-26 13:54 UTC, IvanFesenko commented on src/styles/blocks/card.scss
> +    width: 166px;
```suggestion

```

2024-01-26 13:54 UTC, IvanFesenko commented on src/styles/blocks/card.scss
> +    font-family: Roboto, sans-serif;
```suggestion

```

2024-01-26 13:54 UTC, IvanFesenko commented on src/styles/blocks/card.scss
> +    font-weight: 400;
```suggestion

```

2024-01-26 13:54 UTC, IvanFesenko commented on src/styles/blocks/card.scss
> +    font-family: Roboto, sans-serif;
```suggestion

```

2024-01-26 13:54 UTC, IvanFesenko commented on src/styles/blocks/stars.scss
> +    font-family: Roboto, sans-serif;
```suggestion

```

2024-01-26 13:54 UTC, IvanFesenko commented on src/styles/blocks/stars.scss
> +  }
that not beongs to stars block

2024-01-29 12:49 UTC, Leh-02 commented
@IvanFesenko , can you check my new commits, please

2024-01-29 13:51 UTC, closed without merging