add solution
mate-academy/layout_product-cards pull request #4034
Opened 2024-01-29 15:09 UTC by pasha1932

- [DEMO LINK](https://pasha1932.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://pasha1932n.github.io/layout_product-cards/report/html_report/)

2024-01-29 15:13 UTC, pasha1932 commented
- [DEMO LINK](https://pasha1932.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://pasha1932.github.io/layout_product-cards/report/html_report/)

2024-01-29 16:29 UTC, sTorba24 requested changes
Almost good! Lets improve it

2024-01-29 16:29 UTC, sTorba24 commented on src/index.html
> +      >
```suggestion
      <img
        src="./images/imac.jpeg"
        alt="card"
        class="card__image"
      >
```

2024-01-29 16:29 UTC, sTorba24 commented on src/styles/blocks/card.scss
> +    font-family: Roboto, sans-serif;
set it for body or html

2024-01-29 16:29 UTC, sTorba24 commented on src/styles/blocks/card.scss
> +    font-weight: 400;
it's default values, can be removed

2024-01-29 16:29 UTC, sTorba24 commented on src/styles/blocks/card.scss
> +    font-family: Roboto, sans-serif;
and remove then(fix everywhere(

2024-01-29 16:29 UTC, sTorba24 commented on src/styles/blocks/stars.scss
> +  background-position: center;
background-shorthand can be used

2024-01-29 16:29 UTC, sTorba24 commented on src/styles/blocks/stars.scss
> +}
implement all modifiers from task `stars`

2024-01-30 07:18 UTC, etojeDenys approved these changes
good job

2024-01-30 07:18 UTC, etojeDenys commented on src/index.html
> +      >Buy</a>
<img width="1073" alt="Pasted Graphic" src="https://github.com/mate-academy/layout_product-cards/assets/70220667/76c51a44-954a-449a-9324-472cb22adc63">

2024-01-30 07:18 UTC, etojeDenys commented on src/styles/blocks/stars.scss
> +}
```suggestion
.stars--1 .stars__star:nth-child(-n + 1),
.stars--2 .stars__star:nth-child(-n + 2) {
  background-image: url(../images/star-active.svg);
}
```
combine it with a comma

2024-08-02 11:32 UTC, closed without merging