add task solution
mate-academy/layout_product-cards pull request #4077
Opened 2024-02-01 21:34 UTC by Ehulinian

- [DEMO LINK](https://Ehulinian.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://Ehulinian.github.io/layout_product-cards/report/html_report/)

2024-02-02 07:14 UTC, etojeDenys requested changes

2024-02-02 07:14 UTC, etojeDenys commented on src/index.html
> +        <div class="card__price">$2,199</div>
better to use some semantic tags here for text

2024-02-02 07:14 UTC, etojeDenys commented on src/styles/index.scss
> +  background-image: url(/src/images/star-active.svg);
move to another file as a separate block

2024-02-02 07:14 UTC, etojeDenys commented on src/styles/index.scss
> +}
use sass nesting

2024-02-02 07:14 UTC, etojeDenys commented on src/styles/index.scss
> +  --text-secondary-color: #616070;
use sass vars instead of CSS

2024-02-02 11:36 UTC, closed without merging

2024-02-13 11:00 UTC, l4st1m0za approved these changes
Good job, see the comment

2024-02-13 11:00 UTC, l4st1m0za commented on src/styles/blocks/card.scss
> +  }
```suggestion
.card {
  box-sizing: border-box;
  width: 200px;
  border: 1px solid #f3f3f3;
  border-radius: 5px;
  padding: 32px 16px 16px;
  background: #fff;

  &__image {
    display: block;
    margin: 0 auto 40px;
    width: 160px;
    height: 134px;
  }
```

Use SASS nesting like this in **ALL THE CASES**