Develop
mate-academy/layout_product-cards pull request #4080
Opened 2024-02-02 13:57 UTC by TideTwo

- [DEMO LINK](https://tidetwo.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://tidetwo.github.io/layout_product-cards/report/html_report/)

- [x] there 2 BEM blocks `card` and `stars` each in it own file
- [x] SCSS Nesting is used for `elements`, `modifiers` and `pseudo-classes`
- [x] SCSS Variables are used for main values and placed in a **separate file**
- [x] all `stars--N` modifiers work as expected (Highlight first `N` stars)
- [x] Code follows all the [Code Style Rules ❗️](https://mate-academy.github.io/layout_task-guideline/html-css-code-style-rules)

2024-02-05 08:41 UTC, asakevych requested changes
Good job!! :rocket: just some changes are required in html structure :wink:

2024-02-05 08:41 UTC, asakevych commented on src/styles/blocks/card.scss
> +  background-image: url("../images/imac.jpeg");
please use tag img insted and add also alt to it, it will make screen readers know that you have some image of your product :wink:

2024-02-05 08:41 UTC, asakevych commented on src/styles/blocks/card.scss
> +    width: 166px;
you shouldn't define such pixels, just spaces between element, it also would be easier to do when you add `<img>` to your card

2024-02-05 08:41 UTC, asakevych commented on src/styles/blocks/stars.scss
> +  }
nice!! :heart_eyes:

2024-02-06 00:51 UTC, nataliaklonowska requested changes

2024-02-06 09:12 UTC, asakevych requested changes
Great! it seems it should work, but you didn't deploy project, please make deploy and ask for review once more :wink:

2024-02-06 09:16 UTC, TideTwo commented
All i do is click the links in the first request and i get taken to the deployed site, I see it as deployed, showing the tests and the project itself, Could you show me what is shown on your screen? Im not sure how else to resolve this.

![image](https://github.com/mate-academy/layout_product-cards/assets/69630160/1b548684-ecc8-482c-a2fb-321a559381dd)
![image](https://github.com/mate-academy/layout_product-cards/assets/69630160/38bd012e-a0db-41ed-ab64-d15b4136a005)


here are the links again:
[DEMO LINK](https://tidetwo.github.io/layout_product-cards/)

[TEST REPORT LINK](https://tidetwo.github.io/layout_product-cards/report/html_report/)

2024-02-06 09:26 UTC, asakevych requested changes
please make deploy once more, old code is deployed, check with 'inspect' image, it is still is added as a background but it is now added with <img> in your code
you should run deploy after every change you push to repo :wink:

2024-02-06 12:14 UTC, TideTwo commented
Now I understand, apologies for the confusion. I didn't think you meant that the pages have not been updated, but that they were not there at all, so when I saw the page opening, I assumed I had done it properly. @asakevych

2024-02-06 14:26 UTC, nataliaklonowska requested changes
your test report link is not working

2024-02-06 14:26 UTC, nataliaklonowska commented on src/styles/blocks/card.scss
> +    }
hover should be on button instead whole card

2024-02-07 09:21 UTC, nataliaklonowska approved these changes

2025-01-04 13:07 UTC, closed without merging