made a block
mate-academy/layout_product-cards pull request #411
Opened 2020-08-31 12:01 UTC by aionova

- [DEMO LINK](https://aionova.github.io/layout_product-cards/)
 - [TEST REPORT LINK](https://aionova.github.io/layout_product-cards/report/html_report/)

2020-08-31 15:17 UTC, danheim requested changes

2020-08-31 15:17 UTC, danheim commented on src/style.css
> +}
напиши css для всех случаев рейтинга (0 - 5)

2020-08-31 15:17 UTC, danheim commented on src/style.css
> +  margin-top: 20px;
задавай верхнему элементу margin-bottom вместо margin-top текущему

2020-08-31 15:24 UTC, aionova commented on src/style.css
> +  margin-top: 20px;
done)

2020-09-01 13:52 UTC, danheim requested changes
good start

2020-09-01 13:52 UTC, danheim commented on src/index.html
> +        </div>
считаю нужным сделать stars отдельным блоком
```suggestion
        <div class="stars">
          <div class="stars__star"></div>
          <div class="star"></div>
          <div class="star"></div>
          <div class="star"></div>
          <div class="star"></div>
        </div>
```

2020-09-01 13:52 UTC, danheim commented on src/index.html
> +        </div>
Некорректный BEM
У тебя блок и элемент в одном лице, так не может быть

2020-09-01 13:52 UTC, danheim commented on src/style.css
> +  color: black;
black стандартный цвет
остановитесь копировать из фигмы не глядя

2020-09-01 13:52 UTC, danheim commented on src/style.css
> +  background: #fff;
а это стандартный цвет для background

2020-09-01 13:52 UTC, danheim commented on src/style.css
> +  margin-bottom: 20px;
тебе в этом случае не нужен margin-top, действуй только через margin-bottom

2020-09-01 13:52 UTC, danheim commented on src/style.css
> +  background-position: center;
это можно собрать в одно свойство background

2020-09-01 13:52 UTC, danheim commented on src/style.css
> +  background-repeat: no-repeat;
повторяешь код

2020-09-01 14:21 UTC, aionova commented on src/style.css
> +  background-repeat: no-repeat;
спасибо за исправления!

2020-09-02 11:30 UTC, danheim approved these changes
Looks good to me

2023-09-27 08:52 UTC, closed without merging