Develop
mate-academy/layout_product-cards pull request #413
Opened 2020-08-31 12:52 UTC by andlap24

[DEMO LINK](https://andlap24.github.io/layout_product-cards/) <br>
[TEST REPORT LINK](https://andlap24.github.io/layout_product-cards/report/html_report/)

2020-08-31 15:19 UTC, danheim requested changes

2020-08-31 15:19 UTC, danheim commented on src/index.html
> +        >
форматирование отступов

2020-08-31 15:19 UTC, danheim commented on src/index.html
> +        Купить
```suggestion
          Купить
```

2020-08-31 15:19 UTC, danheim commented on src/style.css
> +  padding: 0;
не помещай это в *, для того чтобы сбросить стили есть `reset.css`, погугли

2020-08-31 15:19 UTC, danheim commented on src/style.css
> +  font-family: "Roboto", sans-serif;
кавычки опциональны

2020-08-31 15:19 UTC, danheim commented on src/style.css
> +}
напиши css для всех рейтингов

2020-08-31 15:46 UTC, andlap24 commented on src/style.css
> +}
все поправил. Спасибо.

2020-09-01 13:58 UTC, danheim approved these changes
Good

2020-09-01 13:58 UTC, danheim commented on src/index.html
> +      </div>
обертка лишняя, попробуй без нее

2020-09-01 13:58 UTC, danheim commented on src/style.css
> +  font-style: normal;
normal is a default value for font-style

2020-09-01 13:58 UTC, danheim commented on src/style.css
> +  font-family: "Roboto", sans-serif;
inherit?

2020-09-01 15:57 UTC, andlap24 commented on src/style.css
> +  font-family: "Roboto", sans-serif;
okay, i will solve this and save local

2020-09-01 15:58 UTC, andlap24 commented on src/index.html
> +      </div>
ок, все поправлю. Комитить не буду уже.

2020-10-02 13:35 UTC, closed without merging