add solution
mate-academy/layout_product-cards pull request #4513
Opened 2024-06-19 15:01 UTC by Valentyn-Radobenko

- [DEMO LINK](https://Valentyn-Radobenko.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://Valentyn-Radobenko.github.io/layout_product-cards/report/html_report/)
- [x] there 2 BEM blocks `card` and `stars` each in it own file
- [x] SCSS Nesting is used for `elements`, `modifiers` and `pseudo-classes`
- [x] SCSS Variables are used for main values and placed in a **separate file**
- [x] all `stars--N` modifiers work as expected (Highlight first `N` stars)
- [x] Code follows all the [Code Style Rules ❗️](https://mate-academy.github.io/layout_task-guideline/html-css-code-style-rules)

2024-06-19 16:32 UTC, Moroz-Dmytro requested changes
Use more semantic tags, like `h2`, `ul`, `p`...

2024-06-19 16:32 UTC, Moroz-Dmytro commented on src/styles/card.scss
> +  height: $card-height;
Better not to fix height

2024-06-19 16:32 UTC, Moroz-Dmytro commented on src/styles/card.scss
> +  transition: box-shadow 0.3s;
The order of your styles is important. Here is useful link - https://9elements.com/css-rule-order/

2024-06-19 16:32 UTC, Moroz-Dmytro commented on src/styles/card.scss
> +  background-color: #fff;
Create variable for all colors

2024-06-19 16:32 UTC, Moroz-Dmytro commented on src/styles/card.scss
> +    margin-bottom: 4px;
Use only `margin-top` or `margin-bottom`

2024-06-19 16:32 UTC, Moroz-Dmytro commented on src/styles/card.scss
> +    font-weight: 400;
Add default `font-family` and `font-size` to your `html`, not to repeat it in every class

2024-06-19 16:32 UTC, Moroz-Dmytro commented on src/styles/card.scss
> +    width: 166px;
Do you really need to fix width here?

2024-06-19 16:32 UTC, Moroz-Dmytro commented on src/styles/card.scss
> +    width: 166px;
Do you really need to fix width here?

2024-06-19 16:32 UTC, Moroz-Dmytro commented on src/styles/card.scss
> +    width: 166px;
Do you really need to fix width here?

2024-06-19 16:32 UTC, Moroz-Dmytro commented on src/styles/variables.scss
> +$card-width: 198px; // ширина карти з урахуванням бордюру буде 200px
```suggestion
$card-width: 200px;
```

And add `box-sizing: border-box;`

2024-06-19 16:32 UTC, Moroz-Dmytro commented on src/styles/variables.scss
> +$font-family: Roboto, sans-serif;
Don't need variable for `font-family`

2024-06-20 15:01 UTC, BudnikOleksii approved these changes
Good work 👍

2024-06-20 15:01 UTC, BudnikOleksii commented on src/index.html
> +        alt="iMac"
alt attribute should describe the image content
<img width="471" alt="image" src="https://github.com/mate-academy/layout_product-cards/assets/63243136/8377b064-28b7-4c02-945a-fe5eb68aa79e">

2024-06-25 11:52 UTC, closed without merging