add task
mate-academy/layout_product-cards pull request #4588
Opened 2024-07-13 20:59 UTC by Ren6436

- [DEMO LINK](https://Ren6436.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://Ren6436.github.io/layout_product-cards/report/html_report/)

Unfortunately, I have run out of ideas on how to align the stars and the review text, so I would appreciate any comments. Thank you.

2024-07-14 08:38 UTC, anastasiiavorobiova requested changes
Great work! Feel free to ask for help in the chat to fix tests

2024-07-14 08:38 UTC, anastasiiavorobiova commented on src/styles/blocks/card.scss
> +    background-color: #00acdc;
Consider using variables for repeating colors

2024-07-14 08:38 UTC, anastasiiavorobiova commented on src/styles/blocks/card.scss
> +    color: #fff;
Consider using variables for repeating colors

2024-07-14 08:38 UTC, anastasiiavorobiova commented on src/styles/blocks/card.scss
> +    width: 166px;
```suggestion
    width: 100%;
```

2024-07-14 08:38 UTC, anastasiiavorobiova commented on src/styles/blocks/card.scss
> +      height: 40px;
```suggestion
      background-color: transparent;
      color: #00acdc;
```

2024-07-14 08:38 UTC, anastasiiavorobiova commented on src/styles/blocks/stars.scss
> +  &--4 {
Consider using styles from the previous task to keep modifiers working

2024-07-14 20:49 UTC, vadiimvooo requested changes
Seems like you have not deployed your changes. Please feel free to ask for help in fe_chat.

2024-07-15 07:00 UTC, Ren6436 commented
I had some issues with this branch, so I made a new pull request. Sorry about that.
You can find the link to the new pull request below.

https://github.com/mate-academy/layout_product-cards/pull/4592

> Seems like you have not deployed your changes. Please feel free to ask for help in fe_chat.

2024-07-15 07:12 UTC, lerastarynets requested changes
Pls fix prev comments
Pls ask for help in **fe_chat** if you don't understand something

2024-07-16 04:07 UTC, closed without merging