add task solution
mate-academy/layout_product-cards pull request #4681
Opened 2024-08-15 07:18 UTC by Sholudyvyy

- [DEMO LINK](https://Sholudyvyy.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://Sholudyvyy.github.io/layout_product-cards/report/html_report/)

2024-08-15 07:19 UTC, Sholudyvyy commented
- [x] there 2 BEM blocks `card` and `stars` each in it own file
- [x] SCSS Nesting is used for `elements`, `modifiers` and `pseudo-classes`
- [x] SCSS Variables are used for main values and placed in a **separate file**
- [x] all `stars--N` modifiers work as expected (Highlight first `N` stars)
- [x] Code follows all the [Code Style Rules ❗️](https://mate-academy.github.io/layout_task-guideline/html-css-code-style-rules)

2024-08-15 14:08 UTC, VolodymyrKirichenko requested changes
Overall - good job, but let's improve your code 👍

2024-08-15 14:08 UTC, VolodymyrKirichenko commented on src/index.html
> +      <span class="card__nameofproduct">
Invalid class name. Use another class. For example:
```suggestion
      <span class="card__title">
```

2024-08-15 14:08 UTC, VolodymyrKirichenko commented on src/index.html
> +      <span class="card__productcode">Product code: 195434</span>
the same issue. Invalid class name

2024-08-15 14:08 UTC, VolodymyrKirichenko commented on src/styles/blocks/card.scss
> +    text-align: left;
do u need it?

2024-08-15 14:08 UTC, VolodymyrKirichenko commented on src/styles/blocks/card.scss
> +    padding-bottom: 8px;
you have a lot of micro-indents.
use 1-sided margins for all indents.
For example:

```
< -- block -- > // title
-- margin-bottom --
< -- block -- > // code
-- margin-bottom --
```
use this logic in all the cases

2024-08-15 14:08 UTC, VolodymyrKirichenko commented on src/styles/blocks/card.scss
> +      text-align: right;
the same question - do u need it?

2024-08-18 18:48 UTC, BudnikOleksii requested changes
Good work 👍 
Let's fix your stars block and semantic

2024-08-18 18:48 UTC, BudnikOleksii commented on src/index.html
> +      <span class="card__title">
Use semantic tags where possible instead of just span and div. It looks more important that span

2024-08-18 18:48 UTC, BudnikOleksii commented on src/styles/blocks/stars.scss
> +    background-position: center;
You can use one background property

2024-08-18 18:48 UTC, BudnikOleksii commented on src/styles/blocks/stars.scss
> +      background-image: url(../images/star-active.svg);
Why it's 4? And actually, it doesn't work, it should be the same functionality as in the stars task. if the block has `stars--3z modifier you should show 3 active stars and so on

2024-08-18 18:48 UTC, BudnikOleksii commented on src/index.html
> +          <li class="stars__star stars__star--5"></li>
```suggestion
        <ul class="stars stars--3">
          <li class="stars__star></li>
          <li class="stars__star"></li>
          <li class="stars__star"></li>
          <li class="stars__star"></li>
          <li class="stars__star"></li>
```
It should work like this

2024-08-19 07:27 UTC, BudnikOleksii approved these changes
👍

2024-08-19 07:27 UTC, BudnikOleksii commented on src/index.html
> +      <p class="card__title">
For titles it's better to use some heading tag, for example `h3`

2026-07-29 14:09 UTC, closed without merging