Solution
mate-academy/layout_product-cards pull request #571
Opened 2021-03-27 13:46 UTC by igor-stasiv

- [DEMO LINK](https://igor-stasiv.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://igor-stasiv.github.io/layout_product-cards/report/html_report/)

2021-03-30 06:24 UTC, mgrinko requested changes
Ломается на маленьких экранах

2021-03-30 06:24 UTC, mgrinko commented on src/style.css
> +  margin: 16px 5px 45px;
123123

2021-03-30 06:24 UTC, mgrinko commented on src/style.css
> +  line-height: 15px;
123123

2021-03-30 09:21 UTC, rauzok commented on src/index.html
> +      >
<a
        href="#"
        class="card__button"
        data-qa="hover"
      >

2021-03-30 09:27 UTC, rauzok approved these changes

2021-03-30 09:27 UTC, rauzok commented on src/index.html
> +      <a href="#"
```suggestion
      <a
        href="#"
```

2021-03-30 09:27 UTC, rauzok commented on src/index.html
> +          <img src="images/star.svg" alt="Grey star">
Це іконки, краще використай **background-image**

2021-03-31 15:04 UTC, varseniuk approved these changes
Good job! 👍

2021-03-31 15:04 UTC, varseniuk commented on src/index.html
> +          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
```suggestion
    <meta
      name="viewport"
      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
    >
```

2021-03-31 15:04 UTC, varseniuk commented on src/style.css
> +  margin-left: -4px;
better not to use '-' margins and remove 'margin-left' from your `.rate_stars:first-child`

2024-12-15 15:35 UTC, closed without merging