The task «Product card» was done.
mate-academy/layout_product-cards pull request #633
Opened 2021-04-02 00:51 UTC by BilliZane

### Product card
- [DEMO LINK](https://BilliZane.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://BilliZane.github.io/layout_product-cards/report/html_report/)

2021-04-02 13:35 UTC, senkiv-oleh commented on src/index.html
> +      <div class="product-card__title">Моноблок APPLE A1419 iMac 27" Retina 5K (MNED2UA/A)</div>
краще використовувати тег h2

2021-04-02 13:37 UTC, senkiv-oleh commented on src/index.html
> +        <div class="product-card__price-cost">69 999 грн</div>
тут можна замість div використати <span>

2021-04-02 13:38 UTC, senkiv-oleh commented on src/index.html
> +        alt="APPLE A1419 iMac 27 Retina 5K">
```suggestion
      <img
        class="product-card__img"
        src="./images/imac.jpeg"
        alt="APPLE A1419 iMac 27 Retina 5K"
      >
```

2021-04-02 13:45 UTC, senkiv-oleh commented on src/style.css
> +  width: calc(var(--parent-width) + 30px);
тут можна задати ширину 200px. і прибрати ширину в інших елементах, елементи не можуть бути більшими за 170px

2021-04-02 13:49 UTC, senkiv-oleh commented on src/style.css
> +  line-height: 12.89px;
не впевнений, що потрібно вираховувати цю висоту

2021-04-02 13:50 UTC, senkiv-oleh commented on src/style.css
> +  width: var(--parent-width);
ширину кнопки задай, як 100%, вона розтягнеться на всю доступну ширину

2021-04-04 10:34 UTC, senkiv-oleh approved these changes
Cool!

2021-04-04 10:47 UTC, BilliZane commented
> Cool!

2021-04-05 10:29 UTC, VinnieJ-2k20 requested changes
Add modifier and corresponding styles to Stars block

Your site should support all possible star modifiers `stars--1`, `stars--2` etc.

2021-04-05 10:29 UTC, VinnieJ-2k20 commented on src/index.html
> +        <div class="stars">
You still should use modifier `stars--4` here and style stars accodringly.
```suggestion
        <div class="stars stars--4">
```

2021-04-05 10:29 UTC, VinnieJ-2k20 commented on src/style.css
> +}
```suggestion
.stars--1 > .stars__star:nth-child(-n+1),
.stars--2 > .stars__star:nth-child(-n+2),
.stars--3 > .stars__star:nth-child(-n+3),
.stars--4 > .stars__star:nth-child(-n+4),
.stars--5 > .stars__star:nth-child(-n+5) {
  background-image: url("images/star-active.svg");
}
```

2021-04-06 07:00 UTC, VinnieJ-2k20 requested changes
Видимо, ты слегка не так понял мой комментарий.

Тут в блоке stars нужно было просто переиспользовать один из вариантов из предыдущего задания Stars (тот, который с модификатором `stars--4).` Все модификаторы(--1, --2 и т.д.) в HTML вписывать не надо. При необходимости изменить названия классов так, чтобы они соответствовали методологии БЭМ.

Стили для этого блока тоже нужно было переиспользовать из того же задания, при чем предусмотреть все варианты модификатора (чтобы, если в HTML поменять `stars--4` на, например, `stars--3` - то все работало корректно.

Если возникнут вопросы - пиши в личную тему.

2021-04-06 07:16 UTC, BilliZane commented
Я понятия не имею как правильно встроить эти звёздочки и что вообще от меня
хотят... А ещё. У меня крашатся тесты через раз.

вт, 6 апр. 2021 г. в 10:01, VinnieJ-2k20 ***@***.***>:

> *@VinnieJ-2k20* requested changes on this pull request.
>
> Видимо, ты слегка не так понял мой комментарий.
>
> Тут в блоке stars нужно было просто переиспользовать один из вариантов из
> предыдущего задания Stars (тот, который с модификатором stars--4). Все
> модификаторы(--1, --2 и т.д.) в HTML вписывать не надо. При необходимости
> изменить названия классов так, чтобы они соответствовали методологии БЭМ.
>
> Стили для этого блока тоже нужно было переиспользовать из того же задания,
> при чем предусмотреть все варианты модификатора (чтобы, если в HTML
> поменять stars--4 на, например, stars--3 - то все работало корректно.
>
> Если возникнут вопросы - пиши в личную тему.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/mate-academy/layout_product-cards/pull/633#pullrequestreview-628632703>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APKQIGV6QEQDH7B5SYAT7S3THKWS3ANCNFSM42IBAHJQ>
> .
>

2021-04-06 09:59 UTC, VinnieJ-2k20 approved these changes

2023-09-26 15:06 UTC, closed without merging