Fs may19 dmitry y
mate-academy/layout_product-cards pull request #66
Opened 2019-05-28 05:48 UTC by danheim

- [DEMO LINK](https://danheim.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://danheim.github.io/layout_product-cards/report/html_report/index.html)

2019-05-28 11:56 UTC, mgrinko commented on src/style.css
> +}
Не стоит размазывать стили одного элемента по куче правил
лучше продублировать чем искать где и что применится

2019-05-28 11:58 UTC, mgrinko requested changes
Когда стили каждого блока будут собраны вместе буду смотреть даьлше

2019-05-28 21:52 UTC, danheim commented on src/style.css
> +}
Исправил. Прошу прощения за копии файлов, забыл убрать перед коммитом.

2019-05-29 02:58 UTC, mgrinko commented on src/index.html
> +    </div>
section

2019-05-29 02:58 UTC, mgrinko commented on src/index.html
> +      <h5 class="headline">Моноблок APPLE A1419 iMac 27" Retina 5K (MNED2UA/A)</h5>
почему h5?

2019-05-29 02:59 UTC, mgrinko commented on src/index.html
> +      <div class="stars">
лучше стилизовать `start stars-4` чтобы потом из JS было легче этим управлять

2019-05-29 03:00 UTC, mgrinko commented on src/index.html
> +        <div class="star"><img src="images/star.svg" alt=""></div>
нет это не может быть `img` ведь это не смысловая картинка

2019-05-29 03:01 UTC, mgrinko commented on src/index.html
>  <script type="text/javascript" src="./main.js"></script>
JS пока не нужен

2019-05-29 03:02 UTC, mgrinko commented on src/style.css
> +}
Пиши `display: flex;` прямо в тех элементах где это используется

2019-05-29 03:04 UTC, mgrinko commented on src/style.css
> +}
а зачем тут flex?
они ведь и так в колонку выстраиваются

2019-05-29 03:05 UTC, mgrinko commented on src/style.css
> +  height: 134px;
чтобы не было искажений устанавливают что-то одно или ширину или высоту

2019-05-29 03:06 UTC, mgrinko commented on src/style.css
> +  margin: 30px 20px 45px;
я думаю надо просто горизонтально отцентровать
 а не указывать явно отступы

2019-05-29 03:08 UTC, mgrinko commented on src/style.css
> +  margin: 17px 15px;
а зачем тут margin со всех сторон?

2019-05-29 03:08 UTC, mgrinko commented on src/style.css
> +  margin-left: 4px;
обычно ставят right чтобы не было отступа от края

2019-05-29 03:09 UTC, mgrinko requested changes
Жду исправлений

2019-05-29 03:10 UTC, danheim commented
Благодарю, уже работаю

2019-05-29 22:26 UTC, danheim commented on src/index.html
> +      <div class="stars">
не понял

2019-05-29 22:29 UTC, danheim commented on src/style.css
> +  height: 134px;
при указывании только одного, картинка не растягивается достаточно для прохождения теста

2019-05-30 13:38 UTC, mgrinko commented on src/index.html
> +      <div class="stars">
Не на звезду ставить `active` а на `stars` добавить класс `stars-4`

2019-05-30 13:39 UTC, mgrinko requested changes
У тебя тесты валятся потому что внизу под кнопкой нет отступов

2019-05-30 13:40 UTC, mgrinko commented on src/style.css
> +  align-items: center;
margin: auto;

2019-05-30 13:41 UTC, mgrinko commented on src/style.css
> +  width: 170px;
я думаю кнопка должна занимать всю оставшуюся ширину

2019-05-31 00:29 UTC, danheim commented
Решил не фиксить свой код, а переверстать всё в целом после сегодняшней ретроспективы

2019-05-31 18:41 UTC, vpolets approved these changes
Прийняв

2026-08-23 16:51 UTC, closed without merging