size issues
mate-academy/layout_product-cards pull request #680
Opened 2021-05-27 15:32 UTC by vitaliy-martynyuk

https://vitaliy-martynyuk.github.io/layout_product-cards/
https://vitaliy-martynyuk.github.io/layout_product-cards/report/html_report/

2021-05-27 21:09 UTC, stasianich reviewed
Не хватает ещё:

box-shadow: 0 2px 5px rgba(0, 0, 0, 0.07);

когда наводишь на саму карточку + лишние стили

2021-05-27 21:09 UTC, stasianich commented on src/style.css
> +}
У тебя два класса делаю одно и тоже, можно было стилизовать только картинку.

2021-05-27 21:09 UTC, stasianich commented on src/style.css
> +}
1. Порядок свойств.
2. Зачем выносить margin в отдельную переменную?

2021-05-27 21:09 UTC, stasianich commented on src/style.css
> +}
Порядок свойств

2021-05-27 21:09 UTC, stasianich commented on src/style.css
> +}
Порядок свойств

2021-05-27 21:09 UTC, stasianich commented on src/style.css
> +  margin-right: 4px;
Порядок свойств

2021-05-27 21:09 UTC, stasianich commented on src/style.css
> +
Тебе ж по заданию нужно было 4 звезды, зачем добавил лишнее?

2021-05-27 21:09 UTC, stasianich commented on src/style.css
> +}
1. Не использовал.
2. Порядок свойств

2021-05-28 07:00 UTC, vitaliy-martynyuk commented on src/style.css
> +}
про порядок не зовсім розумію, кинь пж гайд якийсь чи документацію

2021-05-28 07:01 UTC, vitaliy-martynyuk commented on src/style.css
> +}
а margin в мене використовується багато де один і той самий, от я і виніс його окремо

2021-05-28 07:01 UTC, vitaliy-martynyuk commented on src/style.css
> +}
agree

2021-05-28 07:01 UTC, vitaliy-martynyuk commented on src/index.html
> +        <section class="imac">
так в цьому і суть, що в мене вся картка по блоках розбита, і замість аймака можна просто буде вставити бокс айфон

2021-05-28 07:01 UTC, vitaliy-martynyuk commented on src/index.html
> +            class="item-purchase-button__link item-purchase-button__link--decoration"
ну це щоб стилізувати окремо, або застосувати стилі на ішну кнопку

2021-05-28 07:02 UTC, vitaliy-martynyuk commented on src/style.css
> +
ментори просили додати функціонал щоб при зміні числа біля stars--4 мінялась к-сть жовтих зірок

2021-05-28 07:08 UTC, stasianich commented on src/index.html
> +        <section class="imac">
Так тебе тогда придётся менять имя класса, можно ж придумать какое-то имя, типа product, чтобы потом не менять

2021-05-28 07:08 UTC, stasianich commented on src/style.css
> +}
https://codeguide.academy/html-css.html#css-order

2021-05-28 07:10 UTC, vitaliy-martynyuk commented on src/index.html
> +        <section class="imac">
я про те, що весь бокс імак можна ctrl+z, а замість нього вставити бокс іфон

2021-05-28 09:19 UTC, solaryasha commented on src/index.html
> +        <section class="imac">
В цій дискусії я на стороні Стаса, краще дати загальну назву класу, а не якусь дуже специфічну

2021-05-28 09:24 UTC, solaryasha requested changes

2021-05-28 09:24 UTC, solaryasha commented on src/index.html
> +        <section class="imac">
В цій дискусії я на стороні Стаса, краще дати загальну назву класу, а не якусь дуже специфічну

2021-05-28 09:24 UTC, solaryasha commented on src/style.css
> +.image {
card__image

2021-05-28 09:24 UTC, solaryasha commented on src/style.css
> +@import "./variables.css";
Додай ці файли в PR

2021-05-28 09:24 UTC, solaryasha commented on src/style.css
> +  box-sizing: border-box;
Зайве

2021-05-28 09:24 UTC, solaryasha commented on src/style.css
> +.content {
краще вже `page`

2021-05-28 09:24 UTC, solaryasha commented on src/style.css
> +  flex-direction: row;
Дефолтне значення

2021-05-28 09:24 UTC, solaryasha commented on src/style.css
> +}
Дуже багато правил дублюється

2021-05-28 09:24 UTC, solaryasha commented on src/style.css
> +.item-purchase-button__link:hover {
Записуй в псевдокласах тільки ті стилі, які змінюються

2021-05-28 09:24 UTC, solaryasha commented on src/style.css
> +  font-family: "Roboto", sans-serif;
Винеси в html тег

2021-05-28 09:27 UTC, vitaliy-martynyuk commented on src/style.css
> +@import "./variables.css";
а як саме це зробити?

2021-05-28 14:28 UTC, solaryasha requested changes

2021-05-28 14:28 UTC, solaryasha commented on src/style.css
> +}
Ці правила дублюються

2021-05-28 14:43 UTC, vitaliy-martynyuk commented on src/style.css
> +}
якщо я їх приберу,  то нові зірки будуть ставати не на свої місця. зараз у слек скину

2021-05-31 07:49 UTC, danylo-onishchuk requested changes

2021-05-31 07:49 UTC, danylo-onishchuk commented on src/index.html
> +          <div class="item-description__content">
Я бы использовал тут тег заголовка.

2021-05-31 07:49 UTC, danylo-onishchuk commented on src/style.css
> +/* #region iMac*/
Обычно в проектах запрещено добавлять комменты на продакшен. Названия классов должны быть самодокументируемы, чтоб не приходилось добавлять подобные комменты. Delete all comments please :)

2021-05-31 07:49 UTC, danylo-onishchuk commented on src/style.css
> +  line-height: 15.47px;
It`s a magic. Используй только целые значения :)

2021-05-31 07:49 UTC, danylo-onishchuk commented on src/style.css
> +  background-repeat: no-repeat;
Выше ты уже добавил для звездочек правила background-repeat и background-position. :nth-child(n+1) - использовал псевдокласс как надо.

2021-05-31 07:49 UTC, danylo-onishchuk commented on src/style.css
> +.item-purchase-button__link:hover {
border должен быть по дефолту, а не только при hover эффекте.

2021-06-01 13:08 UTC, danylo-onishchuk approved these changes

2021-11-25 08:54 UTC, closed without merging