1 attempt
mate-academy/layout_product-cards pull request #720
Opened 2021-06-03 20:05 UTC by dima-cherednyk

- [DEMO LINK](https://dima-cherednyk.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://dima-cherednyk.github.io/layout_product-cards/report/html_report/)

2021-06-04 11:41 UTC, vkryvytskyy requested changes

2021-06-04 11:41 UTC, vkryvytskyy commented on src/index.html
> +          >
```suggestion
        <img
          class="card__image"
          src="images/imac.jpeg"
          alt="iMac"
        >
```
закрывающая скобка должна быть на одной линии с открывающей

2021-06-04 11:41 UTC, vkryvytskyy commented on src/index.html
> +      <a class="card__link" href="https://www.moyo.ua/monoblok_apple_a1419_imac_27_retina_5k_mned2ua_a/361498.html?drsq=%D0%9C%D0%BE%D0%BD%D0%BE%D0%B1%D0%BB%D0%BE%D0%BA+APPLE++A1419+iMac+27%22+Retina
```suggestion
      <a class="card__link" href="#">Моноблок APPLE A1419 iMac 27" Retina 5K (MNED2UA/A)</a>
```
Можно оставить просто #

2021-06-04 11:41 UTC, vkryvytskyy commented on src/index.html
> +      <a class="card__link" href="https://www.moyo.ua/monoblok_apple_a1419_imac_27_retina_5k_mned2ua_a/361498.html?drsq=%D0%9C%D0%BE%D0%BD%D0%BE%D0%B1%D0%BB%D0%BE%D0%BA+APPLE++A1419+iMac+27%22+Retina
И сделать заголовком этот текст, ссылка пусть будет на картинке

2021-06-04 11:41 UTC, vkryvytskyy commented on src/index.html
> +        </div>
переиспользуй код из задания layout_stars

2021-06-04 11:41 UTC, vkryvytskyy commented on src/index.html
> +      <a data-qa="hover" href="https://www.moyo.ua/monoblok_apple_a1419_imac_27_retina_5k_mned2ua_a/361498.html?drsq=%D0%9C%D0%BE%D0%BD%D0%BE%D0%B1%D0%BB%D0%BE%D0%BA+APPLE++A1419+iMac+27%22+Retina+5K
```suggestion
      <a data-qa="hover" href="#">
```

2021-06-04 11:41 UTC, vkryvytskyy commented on src/style.css
> +}
переиспользуй код из задания layout_stars для стилизации звезд

2021-06-05 14:48 UTC, closed without merging

2021-06-05 14:49 UTC, dima-cherednyk commented
some mistakes.