Develop
mate-academy/layout_product-cards pull request #739
Opened 2021-06-27 12:00 UTC by Dinexpod

[DEMO LINK](https://Dinexpod.github.io/layout_product-cards/)

2021-06-29 12:40 UTC, vkryvytskyy requested changes

2021-06-29 12:40 UTC, vkryvytskyy commented on src/index.html
> +          <div class="stars__row stars--3">
```suggestion
          <div class="stars stars--3">
```
зачем тут row?

2021-06-29 12:40 UTC, vkryvytskyy commented on src/index.html
> +          <div class="card__description">Моноблок APPLE A1419 iMac 27" Retina 5K (MNED2UA/A)</div>
Используй тут тег заголовка, чтобы выделить семантически важный текст на карточке

2021-09-18 17:10 UTC, Dinexpod commented on src/index.html
> +          <div class="stars__row stars--3">
ну подумал типа прописать что строчка из звездочек)

2021-09-18 17:10 UTC, Dinexpod commented on src/index.html
> +          <div class="card__description">Моноблок APPLE A1419 iMac 27" Retina 5K (MNED2UA/A)</div>
понял

2026-05-10 22:10 UTC, closed without merging