Product card was done!
mate-academy/layout_product-cards pull request #748
Opened 2021-07-08 09:57 UTC by illiarerun

- [DEMO LINK](https://illiarerun.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://illiarerun.github.io/layout_product-cards/report/html_report/)

I've used `margin-bottoms` to pass tests, cause backstop doesn't use `gap` property . But i left gaps commented in my code.

2021-07-08 15:28 UTC, set1one requested changes

2021-07-08 15:28 UTC, set1one commented on src/styles/index.css
> +@import "./button-buy.css";
Вроді все ок. Єдине, не знаю чи доречно записувати стилі кожного елемента product card в новому файлі. Скоріше, це стосується цілих секцій або сторінок сайту.

2021-07-08 15:58 UTC, illiarerun commented on src/styles/index.css
> +@import "./button-buy.css";
Так згоден, я на QnA вже поговорив про це, По ідеї перевикористовуватись може тільки кнопка покупки і зірочки рейтингу. Дякую за rewiew <3. Зараз буду перероблювати)

2021-07-12 11:31 UTC, Ihor-Karpyn requested changes
Nice start 🔥

2021-07-12 11:31 UTC, Ihor-Karpyn commented on src/index.html
> +        <div class="product-card__main">
```suggestion
```

redundant

2021-07-12 11:31 UTC, Ihor-Karpyn commented on src/styles/button-buy.css
> +  box-sizing: border-box;
```suggestion
```
move to normalize

```
* {
  box-sizing: border-box;
}
```

2021-07-12 11:31 UTC, Ihor-Karpyn commented on src/styles/page.css
> +}
rename on normalize

2021-07-12 11:31 UTC, Ihor-Karpyn commented on src/styles/product-card.css
> +}
```suggestion
.product-card {
  width: 200px;
  align-items: center;
  padding: 32px 16px 16px;
  border: 1px solid #f3f3f3;
  border-radius: 5px;
  background-color: #fff;
}
```

Remove comments. Why you need flex? Block elements by default become one under another

2021-07-12 11:31 UTC, Ihor-Karpyn commented on src/styles/product-card.css
> +  object-position: center;
```suggestion
  display: block;
  width: 160px;
  height: 134px;
  margin: 0 auto 40px;
  object-position: center;
```

2021-07-12 11:31 UTC, Ihor-Karpyn commented on src/styles/product-card.css
> +  /* gap: 16px; */
remove comment

2021-07-12 11:31 UTC, Ihor-Karpyn commented on src/styles/product-card.css
> +  /* gap: 4px; */
and this

2021-07-12 11:31 UTC, Ihor-Karpyn commented on src/styles/product-card.css
> +  /* gap: 24px; */
and this

2021-07-12 11:31 UTC, Ihor-Karpyn commented on src/styles/stars.css
> +  /* gap: 4px; */
and this

2021-07-12 14:14 UTC, Ihor-Karpyn approved these changes
Great!!!

2021-07-12 14:14 UTC, Ihor-Karpyn commented on src/index.html
> +      <div class="product-card__info">
```suggestion
```

redundant

2021-11-23 12:53 UTC, closed without merging