Develop
mate-academy/layout_product-cards pull request #779
Opened 2021-07-11 12:33 UTC by RomSmile

- DEMO LINK: https://RomSmile.github.io/layout_product-cards/
- TEST REPORT LINK: https://RomSmile.github.io/layout_product-cards/report/html_report/

2021-07-12 15:19 UTC, Oleksandr-Zhitenko commented
когда навожу на кнопку все ползет. задай бордер, чтобы всегда был. пусть он будет цвета бэкграунда. и бокс сайзинг :бордер бокс

2021-07-13 06:58 UTC, dima-tkachenko commented on src/index.html
> +      <div class="item-content item-container__item-content">
дуже складний БЕМ. Нічого не зрозуміло, але дуже цікаво)

2021-07-13 06:58 UTC, dima-tkachenko commented on src/style.css
> +  width: 160px;
для картинок потрібно задавати і ширину і висоту.

2021-07-13 11:23 UTC, RomSmile commented on src/style.css
> +  width: 160px;
В идеале надо только ширину задавать, чтобы не испортить картинку ;)

2021-07-14 15:34 UTC, evgen1sider commented on src/style.css
> +
падінгів по замовчуванню немає.
якщо хтів скинути всюди перенеси на * {} і тудиж box-sizing;

2021-07-14 15:44 UTC, evgen1sider commented on src/index.html
> +          </ul>
list-item виглядаю як купа блоків хоча по суті повинні бути елементами.
дивлячись як називаєш li повинні виглядати десь так: list-stars__item

2021-07-14 15:53 UTC, evgen1sider requested changes
сама картка виглядає непогано та все ж краще перебудуй свій BEM

2021-07-14 17:51 UTC, RomSmile commented on src/index.html
> +    <div class="item-container" data-qa="card">
Не скажу, что это ошибка. Так как это название тоже имеет место быть, оно просто больше)

2021-07-14 17:53 UTC, RomSmile commented on src/index.html
> +          </ul>
list-stars__list-item Если по БЭМ-у
И я не задавал внешних стилей этим блокам, потому не написал потому и задал соотвецтвующие селекторы.

2021-07-14 18:27 UTC, RomSmile commented
Карточка сделана хорошо. Но по БЭМ-у совсем забыл про разпределение внешних и внутренних стилей блока.

2021-07-14 18:41 UTC, MaksymBeliever requested changes

2021-07-14 21:07 UTC, RomSmile commented on src/style.css
> +.item-content__content-respect {
Для меня, всё читабельно, но когда буду верстать в следующие разы, прийму во внимание это)

2021-07-15 14:49 UTC, Ihor-Karpyn requested changes
Almost done

2021-07-15 14:49 UTC, Ihor-Karpyn commented on src/index.html
> +    <div class="item-container" data-qa="card">
```suggestion
    <div class="card" data-qa="card">
```

2021-07-15 14:49 UTC, Ihor-Karpyn commented on src/index.html
> +    <div class="item-container" data-qa="card">
agree

2021-07-15 14:49 UTC, Ihor-Karpyn commented on src/index.html
> +        <div class="content-info item-content__item-info">
```suggestion
```
remove redundant wrappers

2021-07-15 14:49 UTC, Ihor-Karpyn commented on src/index.html
> +          <span class="info-name content-info__info-name">Моноблок APPLE A1419 iMac 27" Retina 5K (MNED2UA/A)</span>
Use semantics tags

```suggestion
          <h2 class="card__title">
            Моноблок APPLE A1419 iMac 27" Retina 5K (MNED2UA/A)
          </h2>
```

2021-07-15 14:49 UTC, Ihor-Karpyn commented on src/index.html
> +          <span class="info-code">Код товара: 195434</span>
```suggestion
          <p class="info-code">
            Код товара: 195434
          </p>
```

2021-07-15 14:49 UTC, Ihor-Karpyn commented on src/index.html
> +          <span class="respect-reviews">Отзывов: 5</span>
```suggestion
          <p class="respect-reviews">
            Отзывов: 5
          </p>
```

2021-07-15 14:49 UTC, Ihor-Karpyn commented on src/index.html
> +        </div>
```suggestion
        <div class="card__price price">
          <h3 class="price__title">
            Цена:
          </h3>
          <p class="price__value">
            69 999 грн
          </p>
        </div>
```

2021-07-15 14:49 UTC, Ihor-Karpyn commented on src/style.css
> +}
Also add padding: 32px 16px 16px

2021-07-15 14:49 UTC, Ihor-Karpyn commented on src/style.css
> +}
```suggestion
  height: 134px;
  display: block;
  margin: 0 auto 40px;
}

```

2021-07-15 14:49 UTC, Ihor-Karpyn commented on src/style.css
> +  align-items: center;
```suggestion
```

flex redundant here, block elements by default located one below other

2021-07-15 14:49 UTC, Ihor-Karpyn commented on src/style.css
> +}
```suggestion
```

redundant

2021-07-15 14:49 UTC, Ihor-Karpyn commented on src/style.css
> +}
```suggestion
.card__title {
  margin-bottom: 2px;

  font-size: 12px;
  line-height: 18px;
  font-weight: 500;
  color: #060b35;
}

```

2021-07-15 14:49 UTC, Ihor-Karpyn commented on src/style.css
> +}
```suggestion
.card__code {
  margin-bottom: 16px

  font-size: 10px;
  line-height: 14px;
  font-weight: 400;
  color: #616070;
}

```

2021-07-15 14:49 UTC, Ihor-Karpyn commented on src/style.css
> +}
```suggestion
.card__rating {
  margin-bottom: 24px;
}

```

2021-07-15 14:49 UTC, Ihor-Karpyn commented on src/style.css
> +}
Move to card rating

2021-07-15 14:49 UTC, Ihor-Karpyn commented on src/style.css
> +.list-item {
```suggestion
.stars__star {

```

2021-07-15 14:49 UTC, Ihor-Karpyn commented on src/style.css
> +.list-stars {
```suggestion
.stars {

```

2021-07-16 07:47 UTC, Ihor-Karpyn requested changes
Be more attentive to my comments, fix your BEM

2021-07-16 07:47 UTC, Ihor-Karpyn commented on src/index.html
> +        <div class="info content-block__item-info">
```suggestion
```

remove redundant wrappers

2021-07-16 07:47 UTC, Ihor-Karpyn commented on src/index.html
> +          <span class="code">Код товара: 195434</span>
For texts and titles use p and h tags, also fix your BEM. 
```suggestion
          <h2 class="card__title">
            Моноблок APPLE A1419 iMac 27" Retina 5K (MNED2UA/A)
          </h2>
          <p class="card__code">
            Код товара: 195434
          </p>
```

2021-07-16 07:47 UTC, Ihor-Karpyn commented on src/index.html
> +        <div class="opinion content-block__opinion">
```suggestion
        <div class="card__raiting">
```

2021-07-16 07:47 UTC, Ihor-Karpyn commented on src/index.html
> +          <ul class="stars opinion__stars stars--4">
```suggestion
          <ul class="stars card__stars stars--4">
```

2021-07-16 07:47 UTC, Ihor-Karpyn commented on src/index.html
> +            <li class="star"></li>
```suggestion
            <li class="stars__star"></li>
```

2021-07-16 07:47 UTC, Ihor-Karpyn commented on src/index.html
> +          <span class="reviews">Отзывов: 5</span>
p for text
```suggestion
          <p class="card__reviews">
            Отзывов: 5
          </p>
```

2021-07-16 07:47 UTC, Ihor-Karpyn commented on src/index.html
> +        </div>
```suggestion
        <div class="price card__price">
          <h3 class="price__title">
            Цена:
          </h3>
          <p class="price__value">
            69 999 грн
          </p>
        </div>
```

2021-07-16 07:47 UTC, Ihor-Karpyn commented on src/style.css
> +}
Be more attentive to my comments

![image](https://user-images.githubusercontent.com/63306833/125911437-5eb2d3cc-a982-4c0a-bab9-20c4133a1050.png)

2021-07-16 07:47 UTC, Ihor-Karpyn commented on src/style.css
> +  align-items: center;
Be more attentive to my comments

![image](https://user-images.githubusercontent.com/63306833/125911501-f45dd141-3d36-4397-aa80-709745da4f05.png)

2021-07-16 07:47 UTC, Ihor-Karpyn commented on src/style.css
> +}
Be more attentive to my comments

![image](https://user-images.githubusercontent.com/63306833/125911534-144f8928-63ba-4841-9701-151db1820221.png)

2021-07-16 07:47 UTC, Ihor-Karpyn commented on src/style.css
> +}
Be more attentive to my comments

![image](https://user-images.githubusercontent.com/63306833/125911582-8c5b0aae-7b20-48fd-afcf-c8b6d5327394.png)

2021-07-20 10:27 UTC, danheim approved these changes

2023-11-04 16:05 UTC, closed without merging