layout_product-cards
mate-academy/layout_product-cards pull request #859
Opened 2021-08-22 16:49 UTC by vlad-shulzhenko

- [DEMO LINK](https://vlad-shulzhenko.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://vlad-shulzhenko.github.io/layout_product-cards/report/html_report/)

2021-08-23 08:21 UTC, yungvitik commented
Не працює посилання на TEST REPORT LINK...

2021-08-23 11:37 UTC, yungvitik commented on src/index.html
> +        <a href="#" class="btn-buy__link">
```suggestion
        <a href="#" class="btn-buy__link" data-qa="hover">
```

2021-08-23 11:38 UTC, yungvitik commented on src/index.html
> +        <a href="#" class="btn-buy__link">
для кнопти треба додати атрибут data-qa="hover" для проходження тесту

2021-08-23 15:39 UTC, OleksiiBlezniuk requested changes
Пропустил файл style.css, не пройдены тесты, не работает hover на ссылке

2021-08-25 12:14 UTC, aliceblunt8 approved these changes

2021-08-25 12:14 UTC, aliceblunt8 commented on src/styles/card.css
> +  padding-top: 4px;
I think it's better to use margin-bottom instead of padding-top to follow native's browser rendering process (from up to bottom)

2021-08-25 12:14 UTC, aliceblunt8 commented on src/styles/card.css
> +  background-position: 50%;
```suggestion
  background-image: url(../images/star-active.svg);
```

2021-08-25 12:14 UTC, aliceblunt8 commented on src/styles/global.css
> +  box-sizing: border-box;
add not to html, but to all elements (use * selector)

2021-08-25 12:14 UTC, aliceblunt8 commented on src/styles/global.css
> +  box-sizing: border-box;
remove, add with * selector

2021-08-31 08:41 UTC, OleksiiBlezniuk approved these changes

2022-12-07 14:57 UTC, closed without merging