card
mate-academy/layout_product-cards pull request #868
Opened 2021-08-23 10:32 UTC by Ruslan-Mykhalchak

[DEMO LINK](https://Ruslan-Mykhalchak.github.io/layout_product-cards/)
[TEST REPORT LINK](https://Ruslan-Mykhalchak.github.io/layout_product-cards/report/html_report/)

2021-08-23 19:26 UTC, lilia-kuleba commented on src/index.html
> +        <span class="price-value">69 999 грн</span>
Мені здається, що тут клас для <span> краще прописати так: card__price-name i  card__price-value. Так буде конкретніше.

2021-08-23 19:39 UTC, lilia-kuleba commented on src/style.css
> +
Зручніше буде помістити в html font-family (щоб задати всій сторінці, а не тільки body) i font-style(щоб нижче уникнути повторів та виконати пункт - Don't use repeated styles. в readme.md).

2021-08-23 19:46 UTC, lilia-kuleba commented on src/style.css
> +  line-height: 16px;
В фігмі присутній пункт text-transform: uppercase;
І я б центрувала через display, justify-content, align-items.

2021-08-23 19:50 UTC, lilia-kuleba commented on src/style.css
> +  box-sizing: border-box;
box-sizing: border-box вже використано у * { }, тому повторювати не потрібно. 
Впринципі, box-sizing: border-box можна застосувати лише у .card

2021-08-23 19:58 UTC, lilia-kuleba requested changes

2021-08-23 19:58 UTC, lilia-kuleba commented on src/style.css
> +  color: #060b35;
3 найпоширеніших color краще краще прописати в html. Наприклад:--color-dark-blue: #060b35;
Так ми знову ж дотримаємось - Don't use repeated styles.

2021-08-24 18:00 UTC, OleksiiBlezniuk requested changes

2021-08-25 12:04 UTC, aliceblunt8 approved these changes

2021-08-25 12:04 UTC, aliceblunt8 commented on src/index.html
> +      </a>
```suggestion
      <a href="#"
        class="card__button"
        data-qa="hover"
        >
          КУПИТЬ
       </a>
```

2024-09-29 09:26 UTC, closed without merging