Product cards
mate-academy/layout_product-cards pull request #871
Opened 2021-08-23 17:28 UTC by Mariia-Torkaienko

- [DEMO LINK](https://Mariia-Torkaienko.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://Mariia-Torkaienko.github.io/layout_product-cards/report/html_report/)

2021-08-23 18:25 UTC, roman-toritsyn requested changes

2021-08-23 18:25 UTC, roman-toritsyn commented on src/index.html
> +      <h2 class="product__title">Моноблок APPLE A1419 iMac 27" Retina 5K (MNED2UA/A)</h2>
Не до конца понимаю зачем h2 заголовок. Если h1 - будет главным заголовком на странице, а потом же будут отделы товаров и тд. Не факт, что в карточке будет второй по "главности" заголовок страницы, на которой он будет розмещен. Не уверен, что правильно, но я бы разместил в просто span.

2021-08-23 18:25 UTC, roman-toritsyn commented on src/style.css
> +  max-width: 200px;
Думаю, что карточка должна быть статичной в 200 пикселей шириной.

2021-08-23 18:25 UTC, roman-toritsyn commented on src/style.css
> +  flex-direction: row;
flex-direction: row; - по умолчанию дается по-моему.

2021-08-23 18:25 UTC, roman-toritsyn commented on src/style.css
> +  margin: 0 2px;
Может здесь, как в старсах нужно убрать отступ справа у последней звезды?

2021-08-25 07:37 UTC, OleksiiBlezniuk requested changes
Нужно кое-что исправить🙂

2021-08-25 07:37 UTC, OleksiiBlezniuk commented on src/index.html
> +      </div>
Думаю что этот контейнер не должен быть самостоятельным блоком, так как вряд-ли он будет использоваться где-нибудь помимо карточки, сделай его элементом 🙂

2021-08-25 07:37 UTC, OleksiiBlezniuk commented on src/index.html
> +      </div>
Аналогично

2021-08-25 12:32 UTC, aliceblunt8 approved these changes

2021-08-31 09:03 UTC, OleksiiBlezniuk approved these changes

2023-06-23 21:43 UTC, closed without merging