Homework
mate-academy/layout_product-cards pull request #905
Opened 2021-09-12 11:11 UTC by cyb1ove

- [DEMO LINK](https//cyb1ove.github.io/layout_product-cards/)
- [TEST REPORT LINK](https://cyb1ove.github.io/layout_product-cards/report/html_report/)

2021-09-13 11:03 UTC, DionStrzh requested changes
1. Исправь стилизацию бордера кнопки
2. Добавь стили с key-info элементам

2021-09-13 11:03 UTC, DionStrzh commented on src/index.html
> +      <div class="product_card__title key_info key_info--size_m key_info--weight_m key_info--main">
Как понимаю, у тебя key-info переиспользуется в разных элементах для внутренней стилизаций. 
Пиши сразу стили к элементу. Мысль похожа как в Atomic. но у тебя, получается, внутренние стили элемента зависят от дополнительного класса.

2021-09-13 13:47 UTC, DionStrzh approved these changes
Nice one!

2021-09-13 13:49 UTC, solaryasha requested changes

2021-09-13 13:49 UTC, solaryasha commented on src/style.css
> +.product-card {
Окремий бем блок - окремий файл

2021-09-13 13:49 UTC, solaryasha commented on src/style.css
> +.rate-stars {
Окремий бем блок - окремий файл

2021-09-14 10:50 UTC, Aleksey060790 commented
The task are done! Good job!

2021-09-14 12:17 UTC, solaryasha approved these changes

2021-09-14 12:17 UTC, solaryasha commented on src/styles/blocks/product-card.css
> +}
Додавай пустий рядок в кінці файла

2021-09-14 12:17 UTC, solaryasha commented on src/styles/normalize.css
> +}
Додавай пустий рядок в кінці файла

2025-01-20 16:44 UTC, closed without merging